### ISSUE TITLE
Remove unused php/css/js shortcodes, or make DRY

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-developer#116]
I don't see anywhere that the `[php]` et al shortcodes are being used, it seems like `[code]` is always used. If that's correct, it seems like we could remove them.

If there are still uses, then it looks like we could remove all the duplicate code and just make them wrappers for `do_shortcode_code()`. That'd ensure changes like #101 are done consistently

**Comment by ryelle** [comment]
`php` is used in the user-submitted code. +1 to a helper function to avoid repetition though.

**Comment by iandunn** [comment]
Ah, that's what I was missing, thanks!
