### ISSUE TITLE
Update comment code blocks to use new control.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#118]
Users can post code blocks in the comments. We should probably update that to use the new control.

![](https://d.pr/i/rMmeKV.png)

**Reproduce**
1. Visit a function
2. Log in and add a comment.

**Comment by ryelle** [comment]
I think you might still have the SyntaxHighlighter Evolved plugin active. It takes over the rendering there and prevents the new block from rendering. It should look like this:

<img width="931" alt="Screen Shot 2022-06-13 at 12 05 37 PM" src="https://user-images.githubusercontent.com/541093/173396530-01d7655f-1210-4617-8a27-d26501f02f59.png">

Edit: Unless you're pointing out a different issue?

**Comment by StevenDufresne** [comment]
Got it. I tested this in a new environment. Can we remove it from this project?

https://github.com/WordPress/wporg-developer/blob/391dd4b1f08fc6221be927107a8acb3b96f2a872/composer.lock#L264

**Comment by ryelle** [comment]
I think this question https://github.com/WordPress/wporg-developer/issues/84 is still open — I haven't noticed any issues, but I also haven't explicitly tested it.

**Comment by StevenDufresne** [comment]
I see. Hmm. In a new environment, you'll definitely run into this. Maybe I'll close this and let #84 guide the next steps.

Thanks.
