### ISSUE TITLE
HTML in docblock description is displayed as entities

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-developer#135]
<img width="841" alt="Screen Shot 2022-09-01 at 2 03 48 PM" src="https://user-images.githubusercontent.com/484068/188012676-508be0d2-5e0a-4fe5-ac5d-6b1f43d023cb.png">

It doesn't seem to affect many pages. Here are a few examples:

* http://localhost:8888/reference/functions/_register_theme_block_patterns/#description
* http://localhost:8888/reference/classes/wp_ajax_response/add/#description

When it appear in a filter comment, though, it's displayed correctly. http://localhost:8888/reference/functions/_navigation_markup/#source

**Comment by iandunn** [comment]
It looks like it works fine when processed by Code Syntax Block, but not by Syntaxhighlighter Evolved. What was the plan for those?

**Comment by StevenDufresne** [comment]
> It looks like it works fine when processed by Code Syntax Block, but not by Syntaxhighlighter Evolved. What was the plan for those?

I don't think anything is logged or discussed.

**Comment by ryelle** [comment]
> It looks like it works fine when processed by Code Syntax Block, but not by Syntaxhighlighter Evolved.

Syntaxhighlighter Evolved should be deactivated because it takes over the rendering from the Code Syntax Block — all code examples should be using Code Syntax Block. Was there somewhere you've noticed that still needs syntax highlighting that Code Syntax Block wasn't covering?

**Comment by iandunn** [comment]
I haven't noticed anything, but haven't looked either. I just saw the bug, and noticed that both plugins were active locally and in prod.

So it sounds like we should deactivate SyntaxHighlighter Evolved on prod, and then remove it from the local env. Is that right? Or do you think there may be something still using it?

I guess deactivating it on prod might need to wait until after we sync this repo to the deploy SVN, though.

**Comment by ryelle** [comment]
Right, it's still used on production because this hasn't been deployed yet. Once these changes are deployed, it'll need to be deactivated. I think other sites might still be using it (make?), so we can't delete it.

> remove it from the local env

This can happen now though 👍🏻

**Comment by adamwoodnz** [comment]
Cannot reproduce with new theme.
