### ISSUE TITLE
Function parameter argument names cannot be correctly selected via double-clicking

### ISSUE THREAD

**Issue by tommyferry** [WordPress/wporg-developer#139]
When functions have parameter(s) which are associative arrays (e.g. an `$args` parameter with named arguments) the formatting of the "sub-argument" list in HTML appears like so:
```
<code>numberposts</code><span class="type">int</span><div class="desc">Total number of posts to retrieve[...]
```
(Taken from https://developer.wordpress.org/reference/functions/get_posts/)

The lack of whitespace between the initital closing `</code>` tag and the following opening `<span class="type">` tag means the two words (the argument name and type) are both selected when double-clicking on the argument name:

![Screenshot 2022-09-13 at 16 01 36](https://user-images.githubusercontent.com/7941932/189936679-3535f7c0-8df4-4fcb-869d-6df2fb937496.jpg)

Adding whitespace here would mean the names can be easily selected by double-clicking on them. I believe this could be easily resolved by adding a single space to the end of the string here: https://github.com/WordPress/wporg-developer/blob/34e370515f48dab03a0c4fd444bff1c4e151f52c/source/wp-content/themes/wporg-developer/inc/formatting.php#L600

I would expect that some CSS would also need to be updated to account for the increased whitespace, likely here: https://github.com/WordPress/wporg-developer/blob/259ff750ceb24e119a095ff35711ce0349c468a2/source/wp-content/themes/wporg-developer/scss/main.scss#L1085

**Comment by dd32** [comment]
Fixed via 4b34120e6e7073f6c06e8175f34205987343b09a

There is now extra whitespace between the items, however, it now matches between parameters (`$args  array`) and types and hash parameters and types (`numberposts int`)
