### ISSUE TITLE
Sticky code block header overlaps code section

### ISSUE THREAD

**Issue by nielslange** [WordPress/wporg-developer#146]
## Problem

With #125, the CSS of the code block header had been adjusted to make it sticky. Since this change, the code block header overlaps the code section. Removing `position: sticky;` on https://github.com/WordPress/wporg-developer/blob/622b28da9be14acd28e48f71794ce5ccbaa7ed3c/source/wp-content/themes/wporg-developer/scss/prism.scss#L212 solved the problem on my end.

## Steps to reproduce

1. Go to https://developer.wordpress.org/themes/theme-security/using-nonces/.
2. Look up the code examples.

## Expected behaviour

The code block header should not overlap the code section.

## Current behaviour

The code block header overlaps the code section.

## Screenshots

<table>
<tr>
<td>Chrome:
<br><br>

<img width="1440" alt="Screenshot 2022-10-22 at 14 11 46" src="https://user-images.githubusercontent.com/3323310/197325929-1e894f07-5945-4dbe-b966-83945ffbd68b.png">
</td>
<td>Firefox:
<br><br>

<img width="1442" alt="Screenshot 2022-10-22 at 14 13 01" src="https://user-images.githubusercontent.com/3323310/197325968-fab2e1ff-a7a7-4b3e-bb83-dc48e797078e.png">
</td>
<td>Opera:
<br><br>

<img width="1439" alt="Screenshot 2022-10-22 at 14 12 25" src="https://user-images.githubusercontent.com/3323310/197325948-b89a416c-51d6-4116-a8a2-0e6b01bd5d72.png">
</td>
<td>Safari:
<br><br>

<img width="1443" alt="Screenshot 2022-10-22 at 14 12 03" src="https://user-images.githubusercontent.com/3323310/197325938-edc7f7af-75e4-4985-9761-458b7ef91f95.png">
</td>
</tr>
</table>

## System specs

- macOS 12.6 (with M1 chip)
- Chrome 106.0.5249.119 (Official Build) (arm64)
- Firefox 106.0.1 (64-bit)
- Opera 92.0.4561.21 (arm64)
- Safari 16.0 (17614.1.25.9.10, 17614)

cc: @renintw & @ryelle

**Comment by ryelle** [comment]
It looks like the content in this page is wrapped in an extra `pre` tag, which is also causing the extra-large grey space around the code. I don't see this issue on the few other pages I checked (for example, [data validation](https://developer.wordpress.org/themes/theme-security/data-validation/)), so I think it's a content issue.

**Comment by outdoor2kode** [comment]
Yeah, the extra `pre` makes the layout wrong.
I've adjusted the content, and it should be fixed now.
The text was set to `Preformatted`, and it's supposed to just be `Paragraph`.
<img width="1686" alt="image" src="https://user-images.githubusercontent.com/18050944/197565552-63bd5613-7f17-475d-b03b-c555080f1468.png">

**Comment by nielslange** [comment]
Thanks for your replies, @ryelle and @renintw. I can confirm that the issue is fixed by changing the text from `Preformatted` to `Paragraph`. Given that this issue is resolved, I'll mark it as closed.
