### ISSUE TITLE
Layout: Handbooks

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#161]
This is a big issue that should likely be broken up into multiple ones.

**Handbooks**
- [ ] Block editor
- [ ] Themes
- [ ] Plugins
- [ ] APIs
- [ ] Admin

## Screenshot

[Figma Link](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Pages?node-id=1246%3A11634&t=pS0XoTexhVvCl9Ft-0)

![image](https://user-images.githubusercontent.com/1657336/212214601-8bf9bde1-8def-4c94-bfa9-941e159c9342.png)

**Comment by ryelle** [comment]
@jasmussen How should the content here shift on mid-smaller screens? This mockup is 1440px wide, but what should happen on a 1300px or 1200px wide screen? For reference, at 1200px on [Documentation (with only 1 sidebar)](https://wordpress.org/documentation/article/introduction-to-blogging/) it shifts down to one column. A smaller viewport would mean the post content width would need to shrink, and it's already pretty narrow at 680px. The breakdown with one sidebar at 1200px:

```
|      |       main content      |      |      ToC      |      |
| 80px |          680px          | 25px |     335px     | 80px | = 1200px
```

(note, that gap between content & ToC shrinks from 145px to 25px with the viewport)

Sketching out this the same way, unless one of these can shrink more, we need to drop a column at 1440px.

```
|      |   chapters   |      |       main content      |      |      ToC      |      |
| 80px |     260px    | 20px |          680px          | 20px |     300px     | 80px | = 1440px
```

**Comment by jasmussen** [comment]
I think we can probably treat mid-smaller screens same as mobile, and @javierarce had some good concepts there:

> a) hide the chapters on mobile (users will need to use the search function or go to the Developer homepage and then browse through the content) 
> b) display the chapter navigation inside the article (I would need help from you to know the possible locations for the list)
> c) hide the chapter + show an independent breadcrumb navigation above the title that would only appear on mobile

Of those B would appeal the most to me, show it above the main post. What do you think?

**Comment by ryelle** [comment]
Just to be clear, this "mobile" view would be any screen size smaller than 1440px.

I just played around a bit with positioning, and this would be the easiest way to position things without hacky workarounds and to still keep the markup consistent for accessibility. Obviously this isn't totally styled yet, just for placement, but what do you think?

| size | image |
|------|-------|
| Large mobile (600px) | <img width="300" src="https://user-images.githubusercontent.com/541093/215142909-d4d90828-7f8c-4adb-9427-a0ee19254e07.png" /> |
| Small desktop (1024px) | <img width="512" src="https://user-images.githubusercontent.com/541093/215142915-e671c131-d8bc-422e-92ff-ef2115c316d4.png" /> |
| Mid desktop (1280px)  | <img src="https://user-images.githubusercontent.com/541093/215142911-6a70300e-9e82-4913-b0c6-7354eacb888a.png" /> |
| Large desktop (1440px)<br />Three col breakpoint | <img src="https://user-images.githubusercontent.com/541093/215142906-48fb0392-cf16-460e-92d0-8676be241599.png" /> |
| Very large desktop (2000px) | <img src="https://user-images.githubusercontent.com/541093/215142917-2d149e00-b7eb-409e-8395-8fb3daddbaab.png" /> |

**Comment by StevenDufresne** [comment]
Does it make sense to pull out the handbooks into separate tickets?

**Comment by jasmussen** [comment]
> Obviously this isn't totally styled yet, just for placement, but what do you think?

I think chapters as a concept could use a little holistic love, but nothing to prevent launch, IMO. Worth ticketing perhaps for followup? 

Presently, would you be able to add some bottom margin to the chapters box, so at least it pushes the heading downwards when it's in the same column? Something like the same margin as exists between the blue secondary header and the top of the chapter box.

**Comment by ryelle** [comment]
> Does it make sense to pull out the handbooks into separate tickets?

No, I don't think so— I've got a local branch that applies the handbook layout to all the handbooks - and with the go-ahead for the chapters I'll get that PR'd today.

> I think chapters as a concept could use a little holistic love, but nothing to prevent launch, IMO. Worth ticketing perhaps for followup?

Yeah, sounds good.

> Presently, would you be able to add some bottom margin to the chapters box, so at least it pushes the heading downwards when it's in the same column? Something like the same margin as exists between the blue secondary header and the top of the chapter box.

Can do 👍🏻

**Comment by ryelle** [comment]
@StevenDufresne Is there anything still missing from handbook pages?

**Comment by StevenDufresne** [comment]
Everything looks right, or at least ready for review.

I found 2 issues introduced within the context of handbooks that can be addressed here or in a new ticket.

## The article meta links are not working:

https://developer.wordpress.org/redesign-test/rest-api/using-the-rest-api/

<img width="257" alt="Screen Shot 2023-02-10 at 11 11 28 AM" src="https://user-images.githubusercontent.com/1657336/217982862-f15a68ba-7450-4956-be34-384e0adc87d7.png">


## The article meta isn't responsive:

<img width="327" alt="Screen Shot 2023-02-10 at 11 13 59 AM" src="https://user-images.githubusercontent.com/1657336/217983208-295b7bfa-94c5-4f27-89c2-4d18b12d203d.png">

**Comment by ryelle** [comment]
Locally on http://localhost:8888/rest-api/using-the-rest-api/ I do see the edit link… but I noticed the same thing on another article yesterday. Could be a data issue? The link should be replaced by the `wporg-markdown` plugin. 

Unfortunately I can't find any articles with this bug right now to try debugging locally.

**Comment by ryelle** [comment]
Updated the entry-meta wrapping in trunk:

<img width="422" alt="Screenshot 2023-02-10 at 3 56 00 PM" src="https://user-images.githubusercontent.com/541093/218195890-ad565723-4206-4307-9465-1bae13f3bb0e.png">
<img width="634" alt="Screenshot 2023-02-10 at 3 56 14 PM" src="https://user-images.githubusercontent.com/541093/218195893-1293f898-c074-4292-995e-bf6c0834954c.png">

**Comment by StevenDufresne** [comment]
Looks good. Thanks for all the hard work here!
