### ISSUE TITLE
Related block: Incorrect line breaks in uses/used by descriptions

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-developer#180]
<img width="732" alt="Screenshot 2023-01-27 at 3 03 42 PM" src="https://user-images.githubusercontent.com/541093/215186631-3abd1ad8-2d60-4f09-918b-6fa88efd19ff.png">

Source: http://localhost:8888/reference/functions/get_stylesheet/

It looks like this is because the `code` is `display: block`.

**Comment by StevenDufresne** [comment]
Same thing happens to `<a>`. 

Link: https://d.pr/i/F6hfMk

<img width="711" alt="Screen Shot 2023-01-30 at 7 57 21 PM" src="https://user-images.githubusercontent.com/1657336/215458794-9c4a01bc-ed04-4cf0-a51f-cb0bf5e69326.png">
