### ISSUE TITLE
Breadcrumb looks wrong.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#212]
On https://developer.wordpress.org/redesign-test/reference/hooks/activated_plugin/, the `activated_plugin` appears twice and is considered a function!

<img width="557" alt="Screen Shot 2023-02-10 at 12 03 58 PM" src="https://user-images.githubusercontent.com/1657336/217990046-42151aa1-e3a6-4d61-8806-c27228ae0ee6.png">

**Comment by ryelle** [comment]
The first one is `activate_plugin` (no d), and links to the function that filter is called from, so it's technically a correct hierarchy for this filter. I kind of like it, but I see that [does not match production](https://developer.wordpress.org/reference/hooks/activated_plugin/).

<img width="487" alt="Screenshot 2023-02-10 at 8 59 56 AM" src="https://user-images.githubusercontent.com/541093/218110165-a9316e4f-edf4-4fed-ac97-2d11a9b8823c.png">

In brief clicking around, most seemed to use the Function path breadcrumbs. Some filters do say "Hooks  / `filter_name`" 👍🏻  Some say "Classes / Hooks / `filter_name`" — "Classes" there also seems like a bug.

<img width="336" alt="Screenshot 2023-02-10 at 9 02 15 AM" src="https://user-images.githubusercontent.com/541093/218110684-8a533275-af33-43d0-a603-29f53d6ea5c9.png">
<img width="522" alt="Screenshot 2023-02-10 at 9 03 21 AM" src="https://user-images.githubusercontent.com/541093/218110945-885c7c0d-df30-4bc2-893f-5aa787190c68.png">

**Comment by adamwoodnz** [comment]
Don't seem to be able to reproduce this anymore, unsure what has changed. Referring to the examples above:

![Screenshot 2023-10-26 at 4 26 17 PM](https://github.com/WordPress/wporg-developer/assets/1017872/001c2cc6-2d9b-4825-b9c8-70237b0221d7)

![Screenshot 2023-10-26 at 4 26 42 PM](https://github.com/WordPress/wporg-developer/assets/1017872/cf4b7a33-0896-40db-9eef-7b88a8b882b5)

![Screenshot 2023-10-26 at 4 27 37 PM](https://github.com/WordPress/wporg-developer/assets/1017872/5c4456b6-917b-4e0b-a8f4-3c8ce3d3040a)

**Comment by StevenDufresne** [comment]
Okay, we can close and reopen. This will be caught if it still exists.
