### ISSUE TITLE
Update heading font family and size

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#214]
- [ ] Update heading font family to use IBM Plex Mono
- [ ] Audit the sizes (I haven't checked all the differences)

See:
https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?node-id=2014%3A23016&t=PyzR4JGBJ20Mdt9Z-0

**Comment by ryelle** [comment]
This is mostly done already in the branch I used to test the child theme changes: https://github.com/WordPress/wporg-developer/tree/try/local-style-changes -- just need to drop the green paragraphs :)
