### ISSUE TITLE
Update background color to green in some components.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#215]
Some components need a background color change to `#6EC9AE`

## Components
- [x] Homepage callout (although  will be done in #213)
- [ ] Footer (on the homepage, like done in #213)
- [x] Subnav (all pages)

[Figma](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?node-id=2014%3A23016&t=PyzR4JGBJ20Mdt9Z-0)

**Comment by adamwoodnz** [comment]
Green has been removed in final designs
