### ISSUE TITLE
Code blocks should not be collapsed.

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-developer#22]
### Discussed in https://github.com/WordPress/wporg-developer/discussions/4

<div type='discussions-op-text'>

<sup>Originally posted by **StevenDufresne** May 23, 2022</sup>
When we provide code for users, we should assume that all code is relevant and that it's better to see all the code than just a portion of it. I'm sure there are instances where functions are too long. In those cases, maybe we can collapse, or consider not showing the block.

### Screenshot
![](https://d.pr/i/sp15PR.png)</div>

**Comment by StevenDufresne** [comment]
**Huddle Chat Notes:**
- At the very least increase the number of lines shown.
  -  Comments should probably have a lower limit than the official doc blocks
- Could add better logic, for example:
  - <= 15 lines, show all 
  - \> 15 lines < 30, show expand button
  - \> 30 lines, show 20 lines, show expand button 
- Ren: Do we need to have a link below the blocks that does the collapsing? Once you expand, the link disappears to the bottom of the page.
  - Can we maybe click on the block itself to expand/collapse? Maybe a toggle in a different location?

**Comment by ryelle** [comment]
An example of collapse/expand in a different location: https://docs.docker.com/engine/api/v1.41/#operation/ContainerList

<img width="432" alt="Screen Shot 2022-06-01 at 11 18 25 AM" src="https://user-images.githubusercontent.com/541093/171439810-be0155e2-9c46-4f6d-b29d-414bd59e16d9.png">

> Can we maybe click on the block itself to expand/collapse?

For accessibility this would be very tricky to implement, and could have a negative impact on copying the code. Ideally the expand & collapse actions would be `button`s with just the "expand" or "collapse" label.
