### ISSUE TITLE
Archives pages have no search control.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#230]
When we click through to the code archives, including the `since` archive, we get a list of items but the search bar is no longer there. It leaves the user without a tool to filter down results.

| Current | New |
| --- | --- | 
| ![developer wordpress org_reference_functions_ (1)](https://user-images.githubusercontent.com/1657336/222633426-d01d7c3e-eb37-40b5-8c63-ceff6c890d28.png) | ![localhost_8888_reference_hooks_ (2)](https://user-images.githubusercontent.com/1657336/222633415-c4b7f395-3aed-4582-bbb2-41bcd869b0b9.png) |

**Comment by adamwoodnz** [comment]
Will be fixed in #263
