### ISSUE TITLE
Icon alignment issue with notice in content.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#234]
When a handbook has an notice in the content, the icon alignment is incorrect.

**Example**
[Link](http://localhost:8888/block-editor/reference-guides/core-blocks/)

<img width="707" alt="Screen Shot 2566-03-03 at 14 52 00" src="https://user-images.githubusercontent.com/1657336/222642131-7f884a70-c937-4754-aea8-3635b69421b0.png">

**Comment by ryelle** [comment]
It looks like this is [just a simple div with `callout` class](https://github.com/WordPress/gutenberg/blob/0766b79ad07f668ce9a75ed805a75c8eb6a90fa8/docs/reference-guides/core-blocks.md?plain=1#L5-L7), using the style of the old callout shortcode.

I started a PR to replace the callout shortcode with the notice block markup https://github.com/WordPress/wporg-mu-plugins/pull/337 — but that won't actually help here.

Maybe these divs can be replaced with the notice block code on import?

**Comment by adamwoodnz** [comment]
Will be fixed by #315
