### ISSUE TITLE
Table styles missing for in-content tables.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#235]
We are no longer importing all the `devhub` [styles](https://github.com/WordPress/wporg-developer/blob/ec6722b8aac9827a3a4086f19a52d2dd72635514/source/wp-content/themes/wporg-developer-2023/scss/main.scss#L42). As a result, tables are not styled properly in the content.

## Example

Page: [theme-json-living](http://localhost:8888/block-editor/reference-guides/theme-json-reference/theme-json-living/)

<img width="807" alt="Screen Shot 2566-03-03 at 14 57 46" src="https://user-images.githubusercontent.com/1657336/222643049-40b830cc-075b-479e-98c4-bc322122a60b.png">

**Comment by ryelle** [comment]
I wonder if we could figure out a way of wrapping these in `<figure class="wp-block-table">`? It would still need tweaking, but brings back some style.

<img width="716" alt="Screenshot 2023-03-03 at 10 31 04 AM" src="https://user-images.githubusercontent.com/541093/222760691-1432fad8-6968-4cda-bbf5-5432e4abf87e.png">

**Comment by adamwoodnz** [comment]
Will be fixed in #266
