### ISSUE TITLE
Constrain Previous/Next indicators to subnav width.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#241]
The pagination allows you to progress through documents. They currently extend full-width. We should probably consider constraining them to the subnav width. They feel to be totally out of sync with the grid on larger screens.

## Screenshot
<img width="1718" alt="Screenshot 2023-04-27 at 9 19 38 AM" src="https://user-images.githubusercontent.com/1657336/234729132-bf326cb1-dfc2-435e-926c-99261847b755.png">

**Comment by adamwoodnz** [comment]
New design has these aligned with the edges of the content area, see [comment](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp?node-id=2934:7370&mode=dev#521348209).

![Image](https://github.com/WordPress/wporg-developer/assets/1017872/c80da9bd-74b2-4aaa-974c-233b0e1bd264)
