### ISSUE TITLE
Sidebar search bar is truncated.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#242]
The search bar is truncated. 

Example page url: https://developer.wordpress.org/redesign-test/block-editor/

## Screenshot
<img width="333" alt="Screenshot 2023-05-03 at 8 42 50 PM" src="https://user-images.githubusercontent.com/1657336/235906511-00d6061d-05a1-4a8b-b605-e2af5068c98b.png">

**Comment by ryelle** [comment]
Looks better in FF but still not the right width

<img width="383" alt="Screenshot 2023-05-03 at 10 08 17 AM" src="https://user-images.githubusercontent.com/541093/235940570-c2eaa83d-21d8-4c28-8016-64ea2521f41b.png">

----

In documentation, [the search element has a 100% width](https://github.com/WordPress/wporg-documentation-2022/blob/35e9e4669ca2d43630409fbc6ec4a004e0eb4397/source/wp-content/themes/wporg-documentation-2022/parts/search.html#LL1C72-L1C74). That needs to be updated here: 

https://github.com/WordPress/wporg-developer/blob/aa32aeea3f655542a6af341b5238f6bf44912bb7/source/wp-content/themes/wporg-developer-2023/patterns/article-sidebar.php#L12
