### ISSUE TITLE
Code Reference update

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#243]
The spacing between the sections is not consistent and a lot needs to be updated to match the new [design](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?type=design&node-id=2934-6876&mode=design&t=q9aehCWavRMKQ6KF-0):

<img src="https://github.com/WordPress/wporg-developer/assets/1017872/ef4dde85-b5e4-4231-a084-b2296e97e88c" width="400">

Example Url: https://developer.wordpress.org/redesign-test/reference/functions/absint/

## Screenshot

<img width="350" alt="Screenshot 2023-05-03 at 8 49 23 PM" src="https://user-images.githubusercontent.com/1657336/235907882-b419fa63-6097-4397-aeb0-8fbc7b4a91e3.png">

**Comment by adamwoodnz** [comment]
Seems to be more inconsistent layout and duplication below as well

![Screenshot 2023-07-19 at 3 45 37 PM](https://github.com/WordPress/wporg-developer/assets/1017872/4661200d-d1c0-487f-a386-2a3a32d6213d)
