### ISSUE TITLE
User Notes tab "Preview" button separated on to 2 lines.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#244]
The `w` of the Preview button is broken on to 2 lines.

## Screenshot

<img width="462" alt="Screenshot 2023-05-03 at 8 51 55 PM" src="https://user-images.githubusercontent.com/1657336/235908354-d1ba1924-de91-4e34-b2b7-544be847a988.png">

**Comment by adamwoodnz** [comment]
Will be fixed in #243
