### ISSUE TITLE
Code Reference: Hook layout awkward on mobile.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#245]
When a code reference item has a hooks section, the indentation, which was taken from the current site, doesn't look right on mobile (and not that great on desktop either). I'm not sure if removing the margin will fix it.

Example: https://developer.wordpress.org/redesign-test/reference/functions/number_format_i18n/

## Screenshot

<img width="467" alt="Screenshot 2023-05-03 at 8 53 22 PM" src="https://user-images.githubusercontent.com/1657336/235908651-482cba3b-89d5-4a25-8c44-d84ea75420e0.png">

**Comment by adamwoodnz** [comment]
Is this still an issue? I see this on staging

<img src="https://github.com/WordPress/wporg-developer/assets/1017872/6ad53b90-d9f0-43eb-aeec-8ace7af4c94b" width="300">

**Comment by StevenDufresne** [comment]
This is for hooks. I'll update the issue description.

**Comment by joyously** [comment]
This is from a laptop. I think whether it's indented or not, I can't tell which description goes with which hook except by looking at one of the end entries.

![login_header() – Function Developer WordPress org-30](https://github.com/WordPress/wporg-developer/assets/7957680/5ff59b7b-e7a8-4662-8ed8-1c4bcab6018b)

**Comment by adamwoodnz** [comment]
Indentation was fixed by https://github.com/WordPress/wporg-developer/commit/fe5fe445716e4977d0a86f93634b4d4d919185bb
