### ISSUE TITLE
Include WordPress Playground on the redesigned page

### ISSUE THREAD

**Issue by adamziel** [WordPress/wporg-developer#247]
The current https://developer.wordpress.org/ lists some resources, but no [WordPress Playground](https://playground.wordpress.net/).

Let's include it! It even has its own page: http://developer.wordpress.org/playground

What is WordPress Playground? Check out this [demo on SOTW](https://youtu.be/VeigCZuxnfY?t=2912).

**Comment by estelaris** [comment]
Can we use the [block default](https://developer.wordpress.org/resource/dashicons/#block-default) dashicon. 
Description:
**WordPress Playground is WordPress that runs in JavaScript**
[Documentation](https://developer.wordpress.org/playground/)

**Comment by StevenDufresne** [comment]
Added as the last item?

**Comment by StevenDufresne** [comment]
Updated. 

I didn't use `WordPress Playground is WordPress that runs in JavaScript` since that's not entirely true and not used anywhere else as such. I went with an abbreviated version of the subtitle on `https://developer.wordpress.org/playground/`, `WordPress that runs entirely in your browser.`.

I'll close this but reopen with any additional changes. Thanks!

**Comment by adamziel** [comment]
Thank you @StevenDufresne!

> I didn't use WordPress Playground is WordPress that runs in JavaScript since that's not entirely true and not used anywhere else as such.

I am experimenting with that message because it is a useful simplification. “In the browse” doesn’t tell the full story – Playground runs in the browser but also in Node, vs code, mobile apps etc.

I just wanted to clarify that – we can keep the link label as it is.

**Comment by StevenDufresne** [comment]
Yeah fair enough. Feel free to find what fits and we can update. 

To me, "WordPress Playground is WordPress that runs in JavaScript" makes it sounds like a front end library... but I am but one interpreting brain. :)

Relevant Vocabulary:
- Embedded
- Web Component
- Serverless 
- No Server
- Portable
- View


... :)

**Comment by estelaris** [comment]
Thank you @StevenDufresne. 
While Adam works on the exact message, I think we can manage with what you wrote. We will work on the messaging for the site redesign.
Right now, the most important thing was to give a home to the Playground in the developers site.
