### ISSUE TITLE
Code blocks should look like code blocks.

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-developer#25]
### Discussed in https://github.com/WordPress/wporg-developer/discussions/5

# Next Step

- Create PR with updates to code block styles 
  - Should probably have a background
  - Line numbers could probably be removed (especially for non source blocks)
 

<div type='discussions-op-text'>

<sup>Originally posted by **StevenDufresne** May 22, 2022</sup>
It's typical for code blocks to be given more contrast with the document to indicate that you are looking at code. It helps users identify code quickly when scanning a document.

| Ours| Others|
| --- | --- |
|  ![](https://d.pr/i/SrPULM.png) | ![](https://d.pr/i/Yp5ROa.png)  |
| ![](https://d.pr/i/Ml0C91.png) | ![](https://d.pr/i/AeLFFQ.png) |

 </div>

See https://github.com/WordPress/wporg-developer/discussions/5#discussioncomment-2830291 for notes on style

**Comment by tellyworth** [comment]
@ryelle added screenshots with a suggested middle ground idea here: https://github.com/WordPress/wporg-developer/discussions/5#discussioncomment-2830291

![](https://user-images.githubusercontent.com/541093/170577822-3514e2d9-9155-407b-adb2-13e11f6088f9.png)

**Comment by iandunn** [comment]
Another option for the plugin is https://wordpress.org/plugins/syntax-highlighting-code-block/, which would avoid the need to enqueue JS. At first glance it seems backwards-compatible w/ Markus' plugin.

**Comment by ryelle** [comment]
>  At first glance it seems backwards-compatible w/ Markus' plugin.

Unfortunately it's not, really — it uses different attributes, so dropping it in looses the line numbers, and it uses a different highlighter library so I'd need to rewrite the syntax theme I made.
