### ISSUE TITLE
Small Design issue on the WordPress Org site.

### ISSUE THREAD

**Issue by Himshekhar07** [WordPress/wporg-developer#262]
Hello Team,
I have worked on the WordPress.org site and found one small design issue on the below-mentioned page.

There must be some space between the heading and the content.
Issue Page: [https://developer.wordpress.org/](https://developer.wordpress.org/)

I have prepared a screenshot for this issue.
Issue Screenshot: [ https://share.cleanshot.com/CqGDxn2HYngLt4LcwJrN]( https://share.cleanshot.com/CqGDxn2HYngLt4LcwJrN)

Thanks,

**Comment by coffee2code** [comment]
Thanks for the report. This is a duplicate of #259.
