### ISSUE TITLE
Spacing is not proper and design not look good in mobile

### ISSUE THREAD

**Issue by Himshekhar07** [WordPress/wporg-developer#276]
The spacing is not proper for the container and the design does not look good on mobile.
On this page [https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#other-descriptions](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#other-descriptions)

![CleanShot 2023-09-05 at 18 46 27](https://github.com/WordPress/wporg-developer/assets/73247637/64f2be1a-1750-476c-b592-5cb8d8d81eef)

**Comment by coffee2code** [comment]
I suspect you were reporting the excessive blank space on the left of your screenshot. If so, it was the same issue reported in https://meta.trac.wordpress.org/ticket/6886 (being a general issue with handbooks on developer.wordpress.org) and should be improved now. If you were referencing something else, please provide more details.
