### ISSUE TITLE
CLI pages are broken.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#277]
You get the following when viewing a cli command on trunk:

http://localhost:8888/cli/commands/super-admin/
`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/wp-includes/class-wp-list-util.php on line 168`

Looks like an infinite loop related to loading blocks.

**Comment by adamwoodnz** [comment]
Temporary fix deployed. `the_excerpt` was causing the loop, something to do with the `filter_code_content` filter.
