### ISSUE TITLE
Redirect block theme overview

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-developer#281]
Redirect https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/ to https://developer.wordpress.org/themes/block-themes/

**Comment by ndiego** [comment]
Thanks @adamwoodnz, the [Block Theme](https://developer.wordpress.org/block-editor/how-to-guides/themes/block-theme-overview/) page has been removed from the Block Editor Handbook (https://github.com/WordPress/gutenberg/pull/51071). We want to direct folks to the Themes Handbook for all things related to block theming.

**Comment by adamwoodnz** [comment]
Production redirect is in place, still need to add the same to the redesign branch (`trunk`)
