### ISSUE TITLE
There's an extra "Edit" link appearing in the sidebar

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#296]
See the screenshot below. 

<img width="1310" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/a98d3593-e504-4165-90db-41c9d608f755">

**Comment by ndiego** [comment]
@adamwoodnz I don't seem to have access to add labels, but this needs the `Redesign` label. Thanks!

**Comment by adamwoodnz** [comment]
> this needs the `Redesign` label

Added and also added to milestone, thanks :)

**Comment by adamwoodnz** [comment]
This is being added by https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-markdown/inc/class-editor.php#L73

For some reason it's being added in the Chapter List as well as the h1. Temporarily toggling the filter in the Chapter List could be a solution.

**Comment by adamwoodnz** [comment]
Will be fixed by #339
