### ISSUE TITLE
Fix sticky local nav and breadcrumbs after global header update

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-developer#298]
When https://github.com/WordPress/wporg-mu-plugins/pull/466 merges, it will unstick the global header and only stick the local nav (and breadcrumbs). This will affect the way the local navigation bar stickiness works on the Developers site, because it uses the `is-sticky` helper class. Instead, it can now use `"position":{"type":"sticky"}` to use the gutenberg sticky behavior.

![Screen Shot 2023-10-04 at 16 06 31](https://github.com/WordPress/wporg-developer/assets/541093/957cd067-7aa4-4f99-afef-01458167a02a)

See https://github.com/WordPress/wporg-documentation-2022/pull/71 for a similar fix on documentation.

**Comment by adamwoodnz** [comment]
Closed by #348
