### ISSUE TITLE
Provide search "scope" from landing page and beside the search box

### ISSUE THREAD

**Issue by juanmaguitar** [WordPress/wporg-developer#309]
![Screenshot 2023-10-31 at 15 24 44](https://github.com/WordPress/wporg-developer/assets/422576/ffff5401-f39f-4364-ae9f-41d23efe1b1f)

Search from the landing page takes you by default to the search results of Code Reference and from there you can select the site you want search from (Code Reference, Block Editor Handbook...)
![Screenshot 2023-10-31 at 15 25 12](https://github.com/WordPress/wporg-developer/assets/422576/547ccd48-0484-4e1d-a34a-3a55bb3e1f0f)

I think this behavior is a bit confusing as, without any further filters, I would expect a search across all available sites under developer.wordpress.org.

As I'm aware of the current complexity of implementing such a search across different sites under developer.wordpress.org I think providing a filter from the landing page would provide a smoother UX

Something like this:

![Screenshot 2023-10-31 at 15 24 44](https://github.com/WordPress/wporg-developer/assets/422576/6948c4f1-ff9d-450a-b0ee-ce3af124a07b)

I also think the dropdown to select the sub-site where the search will be performed should be beside the search box.

@jasmussen @ndiego what do you think?

**Comment by ndiego** [comment]
> I think this behavior is a bit confusing as, without any further filters, I would expect a search across all available sites under developer.wordpress.org.

Yes I agree. I would probably lean towards removing this search field on the homepage. The current site does not have one, and I am not sure how much value this provides without it being a full site search, which could prove challenging to implement. It's also something that could always be added back later, but I wouldn't want this to hold up the launch.
