### ISSUE TITLE
Update styles of Chapter component

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-developer#310]
As described [here](https://github.com/WordPress/wporg-developer/pull/305#issuecomment-1784796554) by @jasmussen in #305, Chapter list component has the following changes:

## Styles

* Smaller chevron (chevron-small) from [the WordPress Design Library](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/WordPress-Design-Library?type=design&node-id=8%3A13&mode=design&t=d3BLmBFQbGJsdwzC-1) to expand / collapse items.
* Chevron pointing right means collapsed, pointing down means open.
* `3px` dot instead of `4px`.
* New space in padding left in the indentation.

![Mockups of Article with Chapters expanded and collapsed](https://github.com/WordPress/wporg-developer/assets/895819/ff603ca5-7509-4d09-ad22-46a69ecbe2f9)

---

## Design
* [Component](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=2555-10577&mode=design&t=yiAlKtoJHOXCRUuJ-4) of item type.
* [Component](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=2555-10584&mode=design&t=yiAlKtoJHOXCRUuJ-4) of item with three levels of indentation.
* [Developer mockups](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?type=design&node-id=2934-6590&mode=design&t=7w1GtutWNO2sHH72-4). Updated with these changes.

**Comment by adamwoodnz** [comment]
Separate issue created for collapsing on mobile #316

**Comment by adamwoodnz** [comment]
Closed by #305
