### ISSUE TITLE
Layout in Articles

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-developer#313]
As described [here](https://github.com/WordPress/wporg-developer/pull/305#issuecomment-1784796554) in #305, Articles' layout has new spacings.

## Spacings
* Chapter and TOC have a width of 232px.
* Post content fills the remaining space.
* Space between each column is 40px.

![Wireframe of Article layout](https://github.com/WordPress/wporg-developer/assets/895819/362327b7-a58d-401b-aa85-d439b536e898)

---

## Design
* [Developer mockups](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?type=design&node-id=2934-6590&mode=design&t=7w1GtutWNO2sHH72-4). Updated with these changes.

**Comment by adamwoodnz** [comment]
Closed by #305
