### ISSUE TITLE
Update callout design to reflect the WordPress.org Design Library

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#315]
The callouts still have the "old" design. The new design is available [here](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=1264-4116&mode=design&t=PXxc0jZv4uQ2fdXW-0), which should ideally be used across all wordpress.org. 

| Current | New Design |
|-|-|
| <img width="642" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/9a0726cf-d265-496f-9d4e-bbf01ce01d0e"> | <img width="739" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/6b199f34-6982-4b05-8774-c2f8fe9a744e">|

I am not sure if this issue should be in this repo or another. @adamwoodnz if the later, let me know where, and I will move this over. Thanks!

**Comment by adamwoodnz** [comment]
I've been looking into this as part of https://github.com/WordPress/wporg-developer/issues/234, and I've found a couple of implementations throughout the handbooks. There are shortcodes like that found in the [Adv Admin landing page](https://developer.wordpress.org/redesign-test/wp-admin/post.php?post=143559&action=edit):

```
[info]If you're interested in improving this handbook, check the Github Handbook repo, the Documentation Issue tracked, or leave a message in the #hosting-community channel at WordPress Slack.[/info]
```

And there is manual callout html like your screengrab above from the [Get started with wp-env page](https://developer.wordpress.org/redesign-test/wp-admin/post.php?post=144726&action=edit):

```
<div class="callout callout-tip">Some projects, like Gutenberg, include their own specific <code>wp-env</code> configurations, and the documentation might prompt you to run <code>npm run start wp-env</code> instead.</div>
```

See's Kelly's [comment](https://github.com/WordPress/wporg-developer/issues/234#issuecomment-1453707278) mentioning her [PR](https://github.com/WordPress/wporg-mu-plugins/pull/337) for replacing the callout shortcode with block markup, which seems effective and low effort. Perhaps moving forward all handbooks should move to using that implementation.

For the callout divs some options could be:
- Replace all current usage with shortcodes
- Add styles to the parent theme to style them like the notice blocks 

Thoughts @ndiego ?

**Comment by adamwoodnz** [comment]
Or actually @ndiego it sounds like your preference is to [use GitHub alert markdown](https://github.com/WordPress/wporg-mu-plugins/issues/549) in handbooks, and have that converted? In that case maybe Kelly's plugin could be expanded to convert both shortcodes and GitHub alert markdown to notice blocks, and we phase out the callout markup usage.

**Comment by ndiego** [comment]
Sorry, I overlooked the earlier ping. 

>...we phase out the callout markup usage

Yeah, I would love to phase this out in favor of a shortcode and/or GitHub alert markdown. The callout markup, while simple enough, can lead to a lot of formatting errors.

If this is possible, I can coordinate updating every instance of the callout markup in the Block Editor Handbook to coincide with the implementation.

**Comment by adamwoodnz** [comment]
I'll see what other handbooks are using. If there is a lot of callout markup usage we'll need to add the new callout styles to the parent theme in the short term anyway, as it seems a big lift to get it all migrated.

**Comment by adamwoodnz** [comment]
| Handbook | Markup type |
|-|-|
| Block Editor | [Callout](https://github.com/search?q=repo%3AWordPress%2Fgutenberg+callout+language%3AMarkdown&type=code&l=Markdown) (migrate to GitHub Alert) |
| Coding standards | [Shortcode](https://github.com/search?q=repo%3AWordPress%2Fwpcs-docs%20%5Binfo%5D&type=code) |
| Adv Admin | [Shortcode](https://github.com/search?q=repo:WordPress/Advanced-administration-handbook+%255Binfo%255D&type=code) |
| Rest API | [Shortcode](https://github.com/search?q=repo%3AWP-API%2Fdocs%20%5Binfo%5D&type=code) |
| WP CLI | N/A |
| Common APIs | ? |
| Themes | ? |
| Plugins | ? |
| Reference | N/A |

Based on this I think we can move forward with using Kelly's shortcode replacement work, and try to extend it to cover GitHub alerts too.

**Comment by adamwoodnz** [comment]
We might be able to remove the dashicons dependency once these are updated.

**Comment by adamwoodnz** [comment]
I tested Kelly's [PR](https://github.com/WordPress/wporg-mu-plugins/pull/337) and it works well for Developer, but unfortunately caused issues on the core handbook, see [comment](https://github.com/WordPress/wporg-mu-plugins/pull/337#issuecomment-1819992059).

Given these issues, I think a good first step would be to just style the callouts to match the designs.

**Comment by ndiego** [comment]
> Given these issues, I think a good first step would be to just style the callouts to match the designs.

Yeah, whatever is the path of least resistance.
