### ISSUE TITLE
Fix chapter list alignment

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#317]
The new design for the chapter list is looking great, but once you expand down a bit, you will notice that the pages are not aligned to the left. This occurs when a page title wraps but can be fixed by applying `flex-shrink: 0` to the `::before` element (I'm sure there are other ways). See the gif below.

![TOC alignment](https://github.com/WordPress/wporg-developer/assets/4832319/b8293304-bbc0-4027-b90c-2382be849026)

**Comment by adamwoodnz** [comment]
@ndiego I think this might be outdated, the Chapter List now looks like this

<img src="https://github.com/WordPress/wporg-developer/assets/1017872/830fb447-badc-4197-be9a-d7c319a8a8eb" width="400">

Please close if so 🙂

**Comment by ndiego** [comment]
Ah gotcha, thanks. Has that change been pushed to the Staging site? If not, no worries, I am just still seeing this:

<img width="579" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/04e0f233-d363-4bc4-9be8-59059ce27efd">

**Comment by adamwoodnz** [comment]
> Has that change been pushed to the Staging site?

It has yeah 🤔 Cleared cache?

**Comment by ndiego** [comment]
Ahh, that was it. Sorry for the confusion. Closing this issue out.
