### ISSUE TITLE
Code Reference: Methods missing for WP_Hook.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#325]
I would expect to see the methods on this page:
https://developer.wordpress.org/redesign-test/reference/classes/wp_hook/

| Current | Staging |
|--------|--------|
| <img width="808" alt="Screenshot 2023-11-03 at 2 37 25 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/057fcbe1-3b4d-4289-ab03-3fa667f00464"> | <img width="828" alt="Screenshot 2023-11-03 at 2 37 20 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/4a31eaec-a76a-47b9-9af8-ef13793bfe66"> |

**Comment by adamwoodnz** [comment]
Yeah we definitely have some content missing, related https://github.com/WordPress/wporg-developer/issues/300#issuecomment-1780375363
