### ISSUE TITLE
Edit Article + Changelog links not working

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#328]
The Improve on Github or the Changelog link is not working in the staging environment.

### Screenshots

<img width="894" alt="Screenshot 2023-11-03 at 2 49 49 PM" src="https://github.com/WordPress/wporg-developer/assets/1657336/46c4df9c-be24-4ecc-afbc-8787878db1c6">

**Comment by outdoor2kode** [comment]
What kind of "not working" is this, it does not open a new tab when clicked?

**Comment by StevenDufresne** [comment]
Weird, they are working now. I wonder if it was a sync issue. We have run the cron jobs a couple of times since this was logged. Reopen if it happens again.
