### ISSUE TITLE
Add anchor indicator

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-developer#33]
### Discussed in https://github.com/WordPress/wporg-developer/discussions/26

<sup>Originally posted by **iandunn** May 28, 2022</sup>
Our pages [already have anchors for deep-linking to sections](https://developer.wordpress.org/reference/classes/wp_query/#properties-and-methods), but it's helpful to show a visual indicator of that.

Example: https://api.slack.com/reference/surfaces/formatting#escaping

![Screen Shot 2022-05-27 at 1 20 16 PM](https://user-images.githubusercontent.com/484068/170784246-4b61ec0e-d3bb-42b6-bb0b-5044f328188c.png)
</div>

**Comment by ryelle** [comment]
FYI, there's already a pattern for this on the handbooks, if you hover or focus over a heading you can see a link icon:

<img width="371" alt="Screen Shot 2022-05-31 at 12 20 53 PM" src="https://user-images.githubusercontent.com/541093/171223932-9951ed44-eb7b-42f3-afa5-121ba6ff5e29.png">

See https://meta.trac.wordpress.org/ticket/6171

**Comment by iandunn** [comment]
Nice, thanks!

**Comment by iandunn** [comment]
I made https://github.com/WordPress/wordpress.org/commit/d90623fc9ad7541ce0cb20185d929e76d8e8aa64 on the production theme, since it fixes a bug there. I'll backport it to this repo, and then add any experimental stuff.

**Comment by joyously** [comment]
As [mentioned on Slack](https://wordpress.slack.com/archives/C02QB8GMM/p1654203529934789) on June 2, the fix caused other problems with the Table of Contents, which are still present.
![code-ref](https://user-images.githubusercontent.com/7957680/172936371-b2679356-7140-4883-b8fb-3175df70f6e9.gif)

Today I noticed also that a heading with a link gets split into two `a` tags which both have a negative margin for the link icon, so the text overlaps. See https://developer.wordpress.org/reference/classes/wp_rewrite/ for an example.
![WP_Rewrite Class WordPress Developer Resources-27](https://user-images.githubusercontent.com/7957680/172936965-33331900-82bc-42dd-b01f-68c0ed8ea6f6.jpg)
