### ISSUE TITLE
Feedback links in sidebar don't work until `Show Feedback` clicked

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-developer#330]
1. Open https://developer.wordpress.org/reference/classes/wpdb/prepare/
2. Click on any of the `Feedback` links in the sidebar. Nothing will happen
3. Click all of the `Show feedback` links
4. Now click any of the `Feedback` links in the sidebar again. They will work this time.

I wonder how useful it is to have those links in the sidebar to begin with? Maybe the simplest solution is to remove them?

**Comment by coffee2code** [comment]
See also https://meta.trac.wordpress.org/ticket/6874

**Comment by coffee2code** [comment]
The feedback links should not be in the sidebar; the link to the User Contributed Notes section is enough.

I think it ended up being an issue with the ToC picking up on the markup used for the feedback. I haven't looked at that code recently, but changing the markup used for feedback seems easier than changing the ToC code to exclude these particular things.

**Comment by adamwoodnz** [comment]
Links no longer present with new theme
