### ISSUE TITLE
Feedback author card not laid out correctly

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-developer#331]
1. Open https://developer.wordpress.org/reference/classes/wpdb/prepare/#comment-2964
2. Click `Show feedback`

<img width="969" alt="Screenshot 2023-11-03 at 8 40 58 AM" src="https://github.com/WordPress/wporg-developer/assets/484068/7afa64ec-f7da-4805-9bfc-1dd7d8ca6bdd">

**Comment by coffee2code** [comment]
Related: https://meta.trac.wordpress.org/ticket/6873

**Comment by coffee2code** [comment]
Fixed in 83f0244.
