### ISSUE TITLE
Large amount of whitespace appears when scrolling in Firefox

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-developer#332]
1. Open https://developer.wordpress.org/reference/classes/wpdb/prepare/ in Firefox
2. Click on `User Contributed Notes`
3. Scroll down. A large amount of whitespace will appear above the `Uses` section
4. Click on `User Contributed Notes` again
5. Scroll down to a note and click `Show feedback`
6. Scroll down half the page and the viewport will jump up to the `Uses` section

https://github.com/WordPress/wporg-developer/assets/484068/d1bef0cf-1e11-4ab4-9c18-d2e5c9cf8bf8

I haven't been able to reproduce this in Chrome

**Comment by adamwoodnz** [comment]
Can't reproduce with new theme
