### ISSUE TITLE
Chapters list: Make sticky, can potentially scroll independently

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-developer#341]
Extracting from [this comment](https://github.com/WordPress/wporg-developer/issues/312#issuecomment-1794214460), the chapters list, just like the Table of Contents, is a useful anchoring point and context for when you are reading a particular document. To that end, it would be useful to have it be sticky and scroll with you down the page, like so:

![280230428-fb4a8568-849c-479b-845e-5442a875e16e](https://github.com/WordPress/wporg-developer/assets/1204802/352129dd-df27-41f8-b14d-0a3b75ca4876)

The main challenge in making this happen is to handle the case where the viewport is small, and a very long chapter list (perhaps made longer through multiple nodes being expanded) is too long for the viewport.

Instead of using JS to measure the height and then un-sticking the chapters list, another solution is to allow the chapters list to scroll independently. Potentially this could also be simpler from an implementation perspective; have the chapters list always span the full 100% available height of the viewport, and then apply scrollbars as needed. The [comment here](https://github.com/WordPress/wporg-developer/issues/312#issuecomment-1794214460) has a code snippet that could potentially help accomplish this in a light-weight way.

This is not urgent or a blocker for the refresh, but would be nice to have.

**Comment by jasmussen** [comment]
Addendum, in an earlier design, we had a bottom border below the search bar, like so:

![maybe remove the border](https://github.com/WordPress/wporg-developer/assets/1204802/60414eed-a34f-4cb3-91f9-c7e881dd4072)

This border, upon reflection, was actually a not needed, sorry about that, so we can go with this:

![maybe](https://github.com/WordPress/wporg-developer/assets/1204802/c3971e14-2e65-4ae9-83cf-4ae93258b0b2)

This is also relevant to https://github.com/WordPress/wporg-developer/pull/336#issuecomment-1794186452 CC: @adamwoodnz

**Comment by fcoveram** [comment]
Coming to reinforce [Joen's comment](https://github.com/WordPress/wporg-developer/issues/341#issuecomment-1794462249).

**Comment by adamwoodnz** [comment]
Done in https://github.com/WordPress/wporg-developer/pull/469
