### ISSUE TITLE
QA: A few cosmetic issues

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-developer#342]
Did a quick round of QA on the work in progress site. Overall it's looking really solid, a huge step forward in every way. I didn't find any big issues, and as such, collecting what I've found so far here in a single issue. But let me know if you'd like me to extract some of these to separate issues. Anything in the "Nice to have" category is not urgent, especially if tricky. In general, all of this feedback applies to both the Developer Resources site, but also to any other section that uses these patterns.

* [x] We should underline related links on hover:

![underline on hover](https://github.com/WordPress/wporg-developer/assets/1204802/42d9a67a-3e24-4432-8db7-228f60878cf2)

---

**Nice to have:** This dropdown could ideally be a button that opened a custom dropdown. 

![long term, be a button](https://github.com/WordPress/wporg-developer/assets/1204802/3d0b2720-9a85-4747-9eaa-daa84db3519e)

![long term, be a custom dropdown](https://github.com/WordPress/wporg-developer/assets/1204802/1860f9f3-8c26-4d59-b098-bbf35042078f)

A smaller fix would be to have the focus style only be as big as the default content side the select, which may also be nontrivial.

---

* [x] The focus, active, and focus+active states for the search box is missing. 

Focus:

![focus](https://github.com/WordPress/wporg-developer/assets/1204802/fab645bc-5015-4da6-beba-6ce955158899)

Focus + active, note that this also causes a layout shift:

![focus plus active gives layout shift](https://github.com/WordPress/wporg-developer/assets/1204802/e7f00c85-1c18-419b-90e3-83b4749c3556)

---

**Nice to have:** hovering the mid-dot in pagination should not be the same as hovering the "Next" button. Shown here, I'm hovering the mid dot.

![hovering the ·](https://github.com/WordPress/wporg-developer/assets/1204802/8f8b4db1-fd80-4c65-9728-d687b65d828e)

The mid-dot is just  meant to be text. It's not a big deal.

---

* [x] Headings in search results should be underlined on hover

![underline on title hover](https://github.com/WordPress/wporg-developer/assets/1204802/f816121b-19c7-49e7-ac67-3bc1d3a582d0)

---

* [x] Back to top should not appear until you've scrolled a bit

![back to top ideally only when scrolled](https://github.com/WordPress/wporg-developer/assets/1204802/87730485-b40d-4b87-b29d-4e3376eee2ca)

_This one is somewhere between nice to have and good to fix for launch. We don't have a "back to top" link on the site today, so if this one is tricky to address, one thing we could do is to just omit the back to top link until such a time as we can implement it with the "appear on scroll" behavior_.

---

* [x] Wrong items linked in the CLI resources

There are 4 items linked in the CLI page that don't seem like they should be there:
![these should probably not be visible on cli commands](https://github.com/WordPress/wporg-developer/assets/1204802/acb0a3a3-4121-4924-8b1b-b33e9563fb73)

---

**Nice to have:** The Edit links are a bit clunky:

![edit links are a bit awkward, maybe just hide in the sidebar -- do we need the icon?](https://github.com/WordPress/wporg-developer/assets/1204802/85748a4b-a8e5-41fd-afdb-fb27542785d4)

I would hide them from the Chapters list, remove the icon, and make them a fixed font-size, say 14px.

---

**Nice to have:** These notices could be better:
![content, but bad](https://github.com/WordPress/wporg-developer/assets/1204802/a0042921-ec6e-4929-b85e-d136871fb5b0)

It's not entirely clear to me if these are "content", and therefore separate from the refresh or not, but noting for reference that the visual style and icon of this yellow notice is incorrect. If it's content, it's nice to have, if it's part of the refresh, we should address it.

You can use [one of these callouts](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=1264%3A4116&mode=design&t=L0wkI72BIImmZxU5-1) instead.

![callouts](https://github.com/WordPress/wporg-developer/assets/1204802/3082c11e-1db9-4582-849a-92bf88dc9621)

---

* [x] Style the JSX/Plain tabs

![unstyled tabs](https://github.com/WordPress/wporg-developer/assets/1204802/b9479c0e-71bf-43f4-8f3a-97df3d71dc8c)

They could look like this:

![can style like this](https://github.com/WordPress/wporg-developer/assets/1204802/4977f7f5-92b8-4317-9dca-39ebc2ac469b)

---

* [x] Fix list item issues with TOC

On [this page](https://developer.wordpress.org/redesign-test/block-editor/reference-guides/block-api/block-deprecation/), the TOC wraps a bit awkwardly:

![awkward toc on block deprecation](https://github.com/WordPress/wporg-developer/assets/1204802/47a9e48f-6ec1-4d30-8253-09b3dd94c212)

There appears to be a nested list margin causing trouble here:
![Screenshot 2023-11-06 at 11 34 05](https://github.com/WordPress/wporg-developer/assets/1204802/534bd7fd-f2fe-47d2-ba89-c64cf3faf277)

Not sure if that's obsolete per [some of the TOC changes discussed here or not](https://github.com/WordPress/wporg-developer/pull/305#issuecomment-1784796554).

---

* [x] The Copy button is a bit big

![copy button a bit big](https://github.com/WordPress/wporg-developer/assets/1204802/c00e6dbb-3499-46ca-bcc2-6750c2d90e60)

I believe this is the pattern to follow:

![Screenshot 2023-11-06 at 11 37 07](https://github.com/WordPress/wporg-developer/assets/1204802/f8c6fbb9-5aff-488e-be10-40188977bf69)

**Comment by adamwoodnz** [comment]
Thanks @jasmussen, great work!

Yeah lots of these are being tracked in other issues, I'll go through and link them up.

**Comment by adamwoodnz** [comment]
> * The Copy button is a bit big

Fixed by #326

**Comment by adamwoodnz** [comment]
> The Edit links are a bit clunky:

Fixed by #346

**Comment by adamwoodnz** [comment]
> * Wrong items linked in the CLI resources

These are there in [prod](https://developer.wordpress.org/cli/commands/), but at the start of the list. Perhaps the bottom (like staging) is better?

![Screenshot 2023-11-09 at 1 36 28 PM](https://github.com/WordPress/wporg-developer/assets/1017872/9f365230-57ea-4bd3-bc8f-dcf01ffa2538)

**Comment by jasmussen** [comment]
> These are there in [prod](https://developer.wordpress.org/cli/commands/), but at the start of the list. Perhaps the bottom (like staging) is better?

Oh, my mistake! 

I'm actually very happy to defer to you or anyone better versed in this content than myself, so we can scratch it from the list. My main confusion was not seeing it at the bottom like the other, but also that those 4 items lack descriptions. Simply adding descriptions would go a long way.

**Comment by adamwoodnz** [comment]
> * Back to top should not appear until you've scrolled a bit

Created a next iteration issue for this https://github.com/WordPress/wporg-mu-plugins/issues/508

**Comment by adamwoodnz** [comment]
> * Fix list item issues with TOC

The ToC styles have been updated in https://github.com/WordPress/wporg-mu-plugins/pull/499, however https://developer.wordpress.org/redesign-test/block-editor/reference-guides/block-api/block-deprecation/ is still not right. Seems like it could be a content issue with that markdown. Needs more digging.

@ndiego if you have time could you please take a look to see whether there is anything unusual there? Other Block Editor pages don't seem to have this issue.

**Comment by adamwoodnz** [comment]
> * The focus, active, and focus+active states for the search box is missing.

@jasmussen which page did you see this on please? We've made some updates to search, so this is possibly fixed.

eg. Focus style on Block Editor Handbook field elements

![Screenshot 2023-11-21 at 9 48 35 AM](https://github.com/WordPress/wporg-developer/assets/1017872/e4a2718a-5684-48a2-9f92-2a8b5403cdd4)

**Comment by adamwoodnz** [comment]
> * The focus, active, and focus+active states for the search box is missing.

Created a new [issue](https://github.com/WordPress/wporg-parent-2021/issues/117) in parent theme for this, it's also present on Showcase.

**Comment by ndiego** [comment]
> @ndiego if you have time could you please take a look to see whether there is anything unusual there? Other Block Editor pages don't seem to have this issue.

@adamwoodnz I think I figured it out. That doc has incorrect headings, an H3 appears before an H2. This seems to break the TOC. I can fix the doc, but perhaps we need a patch for the TOC generator as well? I have no doubt that this could happen again 😅

**Comment by adamwoodnz** [comment]
> * Style the JSX/Plain tabs

Fixed by #352

**Comment by adamwoodnz** [comment]
Closing now, as I believe everything has been addressed or has a separate issue raised.

Haven't previously noted that callouts are covered by https://github.com/WordPress/wporg-developer/issues/315
