### ISSUE TITLE
Update layout to account for large screen sizes

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#343]
The new design looks great on smaller screen sizes but could use a few tweaks on larger screens. Specifically, the chapters list and the TOC box should "stick" to the left and right, respectively, and the content of the page should be centered and constrained to a max-width (960px should work well).

| Current | Goal |
|-|-|
| <img width="2307" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/7d704da8-71fd-4832-82c6-e48049d81c16"> | <img width="2292" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/9c0468e2-7fe3-4a23-93f6-a58691e44b1c"> | 

I took a stab at mocking up the changes, and this is the result. Mobile tweaks will be needed since I just hacked the browser. 

https://github.com/WordPress/wporg-developer/assets/4832319/8879f70e-58ae-47a6-80d1-21f36a8f803b

- The `<main>` Group block layout was set to flow instead of contained. This allows the content to extend to the edge.
- The `<article>` Group block has the following CSS. The `left` width is half the size of the TOC box (this should probably be a variable)
```
    max-width: 960px;
    margin-right: auto;
    margin-left: auto;
    left: -116px;
    position: relative;
```
- The left TOC box was set to `right: var(--wp--preset--spacing--edge-space);`

**Comment by ndiego** [comment]
@jasmussen @fcoveram can you take a peak at this approach when you have a sec and let me know what you think?

**Comment by jasmussen** [comment]
This looks good to me, let's use it across anything that's documentation related. I also suspect @justintadlock will appreciate this, he's often had a keen eye to legibility.

**Comment by fcoveram** [comment]
It looks good to me as well. Eager to see how it behaves on smaller screens.

**Comment by justintadlock** [comment]
That looks pretty good on larger screens.

**Comment by ndiego** [comment]
@adamwoodnz given the impact this update will have on the design for most desktop users, and the comments above, I would like to propose this be an MVP item. Let me know if I can help in any way 🙏

**Comment by adamwoodnz** [comment]
This should include changes to the pagination too, as outlined in #344
