### ISSUE TITLE
Review the design of the footer Prev/Next bar

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#344]
At the bottom of certain pages in the Developer Resources section is a bar for navigating to the Previous and Next doc. In the current implementation, the bar is off-center, which deviates from the original [Figma](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?type=design&node-id=2934-6071&mode=design&t=xTTRwiEjhl9wpRlb-0) design as well as the implementation on the new WordPress [Showcase](https://wordpress.org/showcase/tonal/) site.  

| Figma Design | Current |
|-|-|
| <img width="1088" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/77a3e5cf-a4e4-4c83-8f19-974a66bd5df6"> | <img width="1000" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/b2968a37-4d26-4db4-b214-8552c844e0c5"> |

I defer to @jasmussen and @fcoveram on the ultimate design, but I think it should either be the Figma implementation or match the Showcase for consistency across WP.org.

**Comment by adamwoodnz** [comment]
This layout used to be centered, and took some effort to make off center. A little frustrating to see it has been reverted 😞

**Comment by fcoveram** [comment]
> …I think it should either be the Figma implementation or match the Showcase for consistency across WP.org.

The Figma design looks cleaner. In Showcase, the spacing mirrors the "Related sites" section placed below, but in Articles is visually aligned with the post content area.

**Comment by ndiego** [comment]
> This layout used to be centered, and took some effort to make off center. A little frustrating to see it has been reverted 😞

My apologies for the back and forth @adamwoodnz. Do you know where the off-centered design was proposed? I can't seem to find it.

**Comment by adamwoodnz** [comment]
> Do you know where the off-centered design was proposed? I can't seem to find it.

Hmm, neither can I, even the [issue](https://github.com/WordPress/wporg-developer/issues/266) has the updated design. I swear I didn't imagine it 😅

**Comment by adamwoodnz** [comment]
Will be updated in #343

**Comment by adamwoodnz** [comment]
> Do you know where the off-centered design was proposed? I can't seem to find it.

Finally came across an issue mentioning it https://github.com/WordPress/wporg-developer/issues/241#issuecomment-1696690740

**Comment by fcoveram** [comment]
I think it was part of a previous iteration.
