### ISSUE TITLE
Embed handler is broken on class pages

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-developer#35]
For example https://developer.wordpress.org/reference/classes/atomfeed/embed/

Expected: it should work like https://developer.wordpress.org/reference/functions/apply_filters/embed/

Are there other page types with broken embeds also?

- [ ] fix class embed
- [ ] fix method embed
- [ ] backport to production/canonical theme

**Comment by ryelle** [comment]
Methods on a class are also not working correctly — this is on the PR #59.

<img width="620" alt="Screen Shot 2022-06-02 at 12 21 38 PM" src="https://user-images.githubusercontent.com/541093/171677543-0058eff4-6a7c-4ff9-ae6e-50405b1e750e.png">

Example on production shows a different error: https://developer.wordpress.org/reference/classes/custom_background/admin_load/embed/
