### ISSUE TITLE
Chapters without sub-pages are not aligned correctly in the chapter list

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#350]
This one was tricky to spot since most chapters have sub-pages. But if you view https://developer.wordpress.org/redesign-test/themes/, you will see that chapters without sub-pages are not correctly indented, which make the chapter list confusing. 

<img width="575" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/969b0d47-276f-47a6-a6e3-bfa66e8da274">

@fcoveram what is the intended design here? I do not see a version in [Figma](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?type=design&node-id=2934-6071&mode=design&t=KhAUzamkAaNwz8NT-0) that has top-level chapters without sub-pages.

**Comment by fcoveram** [comment]
Every level has an icon, either open, closed, or dot. Sorry for not adding that in the mockup.

I just updated the [Design Library's component](https://www.figma.com/file/HOJTpCFfa3tR0EccUlu0CM/WordPress.org-Design-Library?type=design&node-id=2766-2788&mode=design&t=iBpQqZWNxaIcKCQt-4). Here is a screenshot.

<img src="https://github.com/WordPress/wporg-developer/assets/895819/8b0daaf3-039c-43e9-9968-fc604b9d0d82" alt="Design of 'Chapters' component" width="300">
