### ISSUE TITLE
JSX/Plain toggle buttons broken in block editor handbook

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-developer#352]
[It was noted that the buttons to toggle between JSX and Plain JS in the block editor are not styled](https://github.com/WordPress/wporg-developer/issues/342), but they are also not toggling the code below.

Example page: https://developer.wordpress.org/redesign-test/block-editor/how-to-guides/block-tutorial/writing-your-first-block-type/

### Screenshots

| Prod | Staging |
|-|-|
| ![Screenshot 2023-11-09 at 1 57 29 PM](https://github.com/WordPress/wporg-developer/assets/1017872/da77c625-3afc-4355-a48f-5f8fd5e9bb7f) | ![Screenshot 2023-11-09 at 1 57 19 PM](https://github.com/WordPress/wporg-developer/assets/1017872/a671c899-b78a-4877-a008-55423d2672e5) |

**Comment by juanmaguitar** [comment]
Noting here that there's a plan to leave only "JSX" version of the examples in the Handbook that is estimated to be completed in the following weeks
See more info at https://github.com/WordPress/gutenberg/issues/55432
cc: @ndiego

**Comment by adamwoodnz** [comment]
> leave only "JSX" version of the examples in the Handbook that is estimated to be completed in the following weeks

Oh that's excellent news. Is it safe to assume we don't need to address this then? Our launch date is Nov 30.

**Comment by adamwoodnz** [comment]
@juanmaguitar ^ 🙂

**Comment by ndiego** [comment]
I "think" all the non-JSX examples in the Block Editor Handbook will be removed by Nov 30. @ryanwelcher would you be able to provide confirmation/context here?

**Comment by ryanwelcher** [comment]
I'll be putting a PR together to remove the vanilla JS examples this week. I'll be sure it's merged before the 30th

**Comment by adamwoodnz** [comment]
Thanks all!

**Comment by ryanwelcher** [comment]
For reference, the [PR is here](https://github.com/WordPress/gutenberg/pull/56121)

**Comment by juanmaguitar** [comment]
@adamwoodnz for reference, this is the PR opened for this: https://github.com/WordPress/gutenberg/pull/56121

**Comment by juanmaguitar** [comment]
It's worth noting here that after https://github.com/WordPress/gutenberg/pull/56121 there will still be some tabs remaining in the Handbook. See `Input`/`Output` tabs at [Global Settings & Styles (theme.json)](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/)

cc: @ndiego

**Comment by ndiego** [comment]
Thanks for spotting this @juanmaguitar 

I do think we can update that page not to use tabs. For example, the WordPress/Gutenberg tabs reference WordPress 5.8 and can probably just be removed. But I do think the tabbing functionality might be useful in certain situations throughout the Handbook, or in other Handbooks. 

@adamwoodnz I image this will require the creation of a custom block, right?

**Comment by adamwoodnz** [comment]
> this will require the creation of a custom block

No, I think it just needs a little script to handle toggling, and some styles for the buttons (design provided on #342).

**Comment by adamwoodnz** [comment]
> It's worth noting here that after [WordPress/gutenberg#56121](https://github.com/WordPress/gutenberg/pull/56121) there will still be some tabs remaining in the Handbook. See `Input`/`Output` tabs at [Global Settings & Styles (theme.json)](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/)

I've created a [PR](https://github.com/WordPress/wporg-developer/pull/381) to add support for this, but I notice that the handbook now seems to have switched from this functionality, I must have misread... do we want it @ndiego @juanmaguitar ?

**Comment by ndiego** [comment]
The PR looks great! We made some changes to the Handbook that removed many of the tabs, but there are still a few related to theme.json and styling that are worth keeping.

**Comment by adamwoodnz** [comment]
Ok, I'll ship the PR then. A [quick search](https://github.com/search?q=repo%3AWordPress%2Fgutenberg%20%7B%25%20codetabs%20%25%7D&type=code) for `{% codetabs %}` doesn't show any, but maybe I've got that wrong.

Yeah I think [this](https://developer.wordpress.org/redesign-test/block-editor/how-to-guides/themes/theme-json/) could do with being reverted to take advantage of the tabs functionality, as it has a lot of input/output content.

**Comment by ryanwelcher** [comment]
> Ok, I'll ship the PR then. A [quick search](https://github.com/search?q=repo%3AWordPress%2Fgutenberg%20%7B%25%20codetabs%20%25%7D&type=code) for `{% codetabs %}` doesn't show any, but maybe I've got that wrong.
> 
> Yeah I think [this](https://developer.wordpress.org/redesign-test/block-editor/how-to-guides/themes/theme-json/) could do with being reverted to take advantage of the tabs functionality, as it has a lot of input/output content.

Agreed. I removed all the tabs as part of https://github.com/WordPress/gutenberg/pull/56121 but I'll put the non-JS ones back in.

**Comment by ryanwelcher** [comment]
Quick follow up here. I have https://github.com/WordPress/gutenberg/pull/56561 in place to address the missing tabs.

**Comment by adamwoodnz** [comment]
> Quick follow up here. I have [WordPress/gutenberg#56561](https://github.com/WordPress/gutenberg/pull/56561) in place to address the missing tabs.

Looks great! Thanks @ryanwelcher
