### ISSUE TITLE
Missing search bar on archive pages

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-developer#358]
There used to be a search bar on archive pages:
<img width="821" alt="image" src="https://github.com/WordPress/wporg-developer/assets/18050944/5f7fb9fd-25de-457a-93fd-ccffda638a8a">

And it doesn't seem obvious on Figma whether there should be a search bar on an archive page. 
However, it seems more consistent to have one.

Examples:
[archive](http://localhost:8888/reference/functions/)
[tax: file](http://localhost:8888/reference/files/wp-activate.php/)
[tax: package](http://localhost:8888/reference/package/atomlib/)

**Comment by adamwoodnz** [comment]
Fixed in https://github.com/WordPress/wporg-developer/pull/340
