### ISSUE TITLE
Search bar: The input should extend longer and the magnifying glass should be aligned to the left.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#360]
In testing: https://github.com/WordPress/wporg-developer/pull/351, I noticed the search bar layout is not correct.

## Screenshot
<img width="359" alt="Screenshot 2023-11-10 at 10 13 43 AM" src="https://github.com/WordPress/wporg-developer/assets/1657336/2126c841-30f1-4f18-8c17-37c71407c87c">

**Comment by adamwoodnz** [comment]
Will be closed by #351
