### ISSUE TITLE
Improve UX of Related section

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-developer#371]
The font size of file paths can be smaller.
A word should not be truncated and then wrapped to the next line.

What do you think @adamwoodnz, it doesn't appear that there's a clear [design instruction](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?type=design&node-id=2934-7281&mode=design&t=WHhMuRzmY0pMRv0q-0) about this. 

<img width="1464" alt="image" src="https://github.com/WordPress/wporg-developer/assets/18050944/47279ad4-cef3-496c-8a3d-6fec4c82f0c5">

**Comment by adamwoodnz** [comment]
Agree that the word breaking is an issue.

The filepath font size is currently 16px (base). Thoughts on changing it to 14px (small) @WordPress/meta-design ?

**Comment by jasmussen** [comment]
14px filepath sounds good. And `word-break: break-all;` for URLs can also be acceptable, IMO, but agree that isn't working for the description, but potentially `word-break: break-word;` might. What do you think?

**Comment by fcoveram** [comment]
+1 to Joen's idea

**Comment by adamwoodnz** [comment]
Thanks, sounds good

**Comment by joyously** [comment]
I saw this and thought it was because I had a smaller window, but it looks the same when I use a full screen, since there appears to be a max-width on the content portion. There is a lot of unused white space on the edges of a large window.
