### ISSUE TITLE
Broken TOC when showing more Used by

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-developer#372]
![ezgif com-optimize](https://github.com/WordPress/wporg-developer/assets/18050944/1787aef1-3052-4ab4-b7ec-e28be1e3c621)

**Comment by outdoor2kode** [comment]
The issue was gone after applying the new design to TOC.

**Comment by adamwoodnz** [comment]
Sorry @renintw, I can still repro on the page in the recording https://developer.wordpress.org/redesign-test/reference/functions/is_admin/

Behaviour is a bit inconsistent depending on how far down you scroll

![Developer toc](https://github.com/WordPress/wporg-developer/assets/1017872/ed0e97b8-93e8-4ac3-ac81-36a043c47956)

**Comment by outdoor2kode** [comment]
> Sorry @renintw, I can still repro on the page in the recording https://developer.wordpress.org/redesign-test/reference/functions/is_admin/
> 

oh... this stealthy little.. Thanks 🕵️
