### ISSUE TITLE
Broken code block sticky header

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-developer#373]
![sticky](https://github.com/WordPress/wporg-developer/assets/18050944/11703054-3cde-4080-88b8-0c47520c6a8a)

**Comment by ndiego** [comment]
Hmm I don't think the header needs to be sticky here.

**Comment by outdoor2kode** [comment]
@ndiego I guess that's for the long expanded code block like [this one](http://localhost:8888/reference/classes/wp_query/#source).

**Comment by ndiego** [comment]
> @ndiego I guess that's for the long expanded code block like [this one](http://localhost:8888/reference/classes/wp_query/#source).

Oh yeah, that makes sense

**Comment by StevenDufresne** [comment]
I agree with Nick, I don't think that needs to stick. I can't imagine viewing a large code block and needing to copy it.

**Comment by outdoor2kode** [comment]
I'm not thinking about copying it but collapsing it. That said, we have the TOC on the side to help go back to the top.
So I guess we all agree to remove the sticky header here? Any other thoughts not to? cc @adamwoodnz @WordPress/meta-design

**Comment by jasmussen** [comment]
I'd agree we can remove it. But if feedback comes to suggest we need it after all, can stick it to the top, rather than below the top as now.
