### ISSUE TITLE
Use IBM Plex Sans for the heading font-family

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#374]
In reviewing the new Developer Resources design, I noticed that the title on the homepage and a few headings at the bottom are in EB Garamond. However, this font is used nowhere else on the site. 

<img width="1174" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/5be17003-e4cf-4341-9373-1b1212dab5a0">

In discussing this issue with @jasmussen and @fcoveram and reviewing alternatives ([see Figma](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?type=design&node-id=4147-7431&mode=design&t=Ew3TwwR0vKOpuD5D-0)), we also identified that the use of IBM Plex Mono for all headings (even heading that are not code) was not ideal. This was only apparent after seeing the staging site live. 

So, to address the EB Garamond issue and the extensive use of IBM Plex Mono for non-code text, the proposed solution is to use IBM Plex Sans for all non-code headings, which includes the homepage title. This would be a new font but would provide some contrast to Inter (used for all other text) while keeping some connective tissue with the `code` font (IBM Plex Mono) used throughout Developer Resources.

### Homepage

| Current | Proposed |
|-|-|
| <img width="1301" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/dc29f88b-d00b-47d2-9c34-402475f3afcf"> | <img width="1299" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/545af96e-2328-4c3d-903e-a86cc37598ea"> |

### Internal Page

| Current | Proposed |
|-|-|
| <img width="1300" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/5c1368c4-2f2e-4f33-a670-34eb81c3f886"> | <img width="1302" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/c81053ac-931a-4f6f-a252-d8be57b808c1"> |

### Code reference page (a heading that is also code)

| Current | Proposed |
|-|-|
| <img width="1298" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/dfd95da9-22ad-4694-acb8-1d2e600b3d32"> | <img width="1301" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/165702aa-39a7-4af2-8454-3bcb53299e1c"> |

### Implementation

IBM Plex Sans will need to be added to the theme, but in some initial tests, the only additional step will be to set `    --wp--custom--heading--typography--font-family: var(--wp--preset--font-family--ibm-plex-sans);` (or whatever the name of the preset variable is).

The IBM Plex Sans will also be used in the redesign of the Developer Blog, so if this issue should instead be logged in the parent theme, let me know, and I'll move it over. Thanks!

**Comment by jasmussen** [comment]
It does make sense to me to either:

* Use this font for the homepage and headings
* Use EB Garamond for the homepage, and headings

In the former case, it adds some character to this design which seems valid and valuable to try.

**Comment by fcoveram** [comment]
I really like the new look. Thanks for bringing up this idea.

**Comment by adamwoodnz** [comment]
> The IBM Plex Sans will also be used in the redesign of the Developer Blog, so if this issue should instead be logged in the parent theme, let me know, and I'll move it over.

We'll need to add the font to the [global fonts in wporg-mu-plugins](https://github.com/WordPress/wporg-mu-plugins/tree/trunk/mu-plugins/global-fonts), new [issue](https://github.com/WordPress/wporg-mu-plugins/issues/506) created there. So this issue will just cover updating this theme to use it.

**Comment by adamwoodnz** [comment]
Seems like we only need regular (400) and semi bold (600), with no italic? Please correct me if wrong.

**Comment by ndiego** [comment]
> Seems like we only need regular (400) and semi bold (600), with no italic? Please correct me if wrong.

Yes, italics is not allowed in Developer Resources 😂
