### ISSUE TITLE
Make deprecated functions more obvious

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-developer#38]
Example: https://developer.wordpress.org/reference/functions/list_cats/

It should be much more obvious that a function is deprecated.

Likewise for deprecated parameters.

**Comment by tellyworth** [comment]
Some parameter examples:

https://developer.wordpress.org/reference/functions/trackback_url/
https://developer.wordpress.org/reference/functions/get_the_excerpt/

**Comment by iandunn** [comment]
➕ 

For functions, we could add a banner at the top of the page.

For params, we could add a similar banner in the Parameters section.

**Comment by dd32** [comment]
Fixed the missing deprecated function warnings via 28f89da
<img width="996" alt="Screen Shot 2022-06-08 at 7 35 33 pm" src="https://user-images.githubusercontent.com/767313/172585280-8f34fb25-fb07-4772-89e2-c142ac2bca7a.png">
