### ISSUE TITLE
Add `<blockquote>` styling

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#390]
Currently, `<blockquote>` only have default browser styles. A good example is the [Deprecations page](https://developer.wordpress.org/redesign-test/block-editor/reference-guides/block-api/block-deprecation/). 

@jasmussen @fcoveram do we have a standard design that could be applied here?

We have a design on Showcase, but not sure that would work well here. Perhaps just the blue line with no additional text styles?

| Current | Showcase |
|-|-|
|<img width="788" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/6306d543-e053-4990-8125-61a956183a23">|<img width="829" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/e19df28d-d91d-453f-ae8c-676b2d3baeef">|

**Comment by jasmussen** [comment]
I'd be tempted to suggest two styles of blockquotes. The a basic one, and an elaborate one. The one in showcase and news are more elaborate.

For the basic one, I'd be tempted to just show `border-left: 1px solid;`.

**Comment by fcoveram** [comment]
Agree with Joen. A left border adds consistency, but keeping the font style simple aligns with the section's look and feel.

**Comment by ndiego** [comment]
> For the basic one, I'd be tempted to just show `border-left: 1px solid;`.

Sounds good. We are using `2px` in other places, so perhaps something like the following? This is the exact styling that's on Showcase, minus the text styles.

```
blockquote {
    border-left: 2px solid var(--wp--preset--color--deep-blueberry);
    margin-left: 0;
    margin-right: 0;
    padding-left: var(--wp--custom--margin--horizontal);
}
```

<img width="969" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/e74d8143-c472-4224-874b-70ea87717508">

**Comment by jasmussen** [comment]
Can be 2px yes, and have the same padding. I'm even okay with the deep blueberry, though my instinct would be currentColor (or omitting the color variable)

**Comment by ndiego** [comment]
Yeah, I have no strong opinion either way. I tried another option with 1px and the default color, as well as one with the border color we use throughout the site. I also reduced the padding a bit. 

```
blockquote {
    border-left: 1px solid var(--wp--preset--color--light-grey-1);
    margin-left: 0;
    margin-right: 0;
    padding-left: var(--wp--preset--spacing--20);
}
```

```
blockquote {
    border-left: 1px solid;
    margin-left: 0;
    margin-right: 0;
    padding-left: var(--wp--preset--spacing--20);
}
```

| Default | Light Grey |
|-|-|
|<img width="375" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/a3b8b730-1cea-4df7-9bc2-7f64e0d68a79">|<img width="341" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/9073eaba-e64a-4f94-8d2d-ef7ffba21f42">|

**Comment by fcoveram** [comment]
I'm drawn to 2px with the default color (darker). The padding reduction works well.

**Comment by ndiego** [comment]
> I'm drawn to 2px with the default color (darker). The padding reduction works well.

Sounds good. That would look like this. Should we move forward with this design?

```
blockquote {
    border-left: 2px solid;
    margin-left: 0;
    margin-right: 0;
    padding-left: var(--wp--preset--spacing--20);
}
```

| Current | Proposed |
|-|-|
|<img width="350" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/0cd9e335-e15f-47f2-a83e-0abf0ca045f3">|<img width="350" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/224755f4-fda7-4972-9afd-927adb6865af">|

**Comment by fcoveram** [comment]
It looks great to me 🚀
