### ISSUE TITLE
Link action broken on user notes and feedback forms once there is a note saved

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-developer#392]
Steps to reproduce

1. Login and find a post which already has a note, eg. https://developer.wordpress.org/redesign-test/reference/classes/atomentry/#comment-12
2. Start to add a new note or leave feedback on an existing note
3. Attempt to add a link by clicking the link button

Expect: modal to open to add the link.

Actual: nothing happens, no modal and no errors in console

Could be related to 2 forms and scripts being loaded on the page.

**Comment by ndiego** [comment]
Yes, I can confirm the issue: 

<img width="500" src="https://github.com/WordPress/wporg-developer/assets/4832319/659e1208-1ad2-4784-91c5-eade9f716218" />
