### ISSUE TITLE
Search autocomplete is not working in Code Reference section

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#395]
I noticed that search autocomplete is not working in the Core Reference section of the site. Note sure if this is due to the staging site or if the site does not yet have this functionality.

| Current | Redesign |
|-|-|
|<img width="687" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/6c52a36a-1024-4fc9-b8e1-15b6fcb16040">|<img width="618" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/557162fb-534c-49c5-94fa-ab8327cf0c69">|

**Comment by adamwoodnz** [comment]
This has broken a couple of times, but was most recently fixed in https://github.com/WordPress/wporg-developer/commit/b79c35285a29aa67472e1de9bd4f082e8fbcd59d
