### ISSUE TITLE
Add back missing code styles in Code Reference

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#397]
I was doing a 1-1 comparison with the redesign and the current site and noticed that some code styles are missing. Note the red `string` and `array` text in the current design. 

| Redesign | Current |
|-|-|
|<img width="831" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/98e423a5-4597-4f93-95d9-5202256004d5">|<img width="840" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/168ae3bb-ccb4-4d15-b4db-220b47a2aec5">|

While this change is correct to the [Figma design](https://www.figma.com/file/2WxlJFzMJvqPfZL1EkAOVp/Developer-Resources?type=design&node-id=3775-11438&mode=design&t=vveWOwItwnMjTLIL-0), I think we should add back the colored styling. It makes these docs easier to parse.

**Comment by adamwoodnz** [comment]
Fixed in https://github.com/WordPress/wporg-developer/commit/fa715cbe374e4eaf1453535534dbcaf1a6708314
