### ISSUE TITLE
The Last Updated date is not displaying on Code Reference docs

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#398]
I'm not sure if this is a bug specifically with the Staging site, but I noticed that the Last Updated date is not displayed on Code Reference docs. Here's an [example](https://developer.wordpress.org/redesign-test/reference/hooks/edited_taxonomy/). 

<img width="717" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/bba2bc0c-33e4-40d2-9127-11f56cb58135">

**Comment by pkevan** [comment]
Looks like this is intentional (as far as the code is concerned): https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-date/index.php#L33-L46

I guess we either need to work around it (and duplicate the date), or only show the last updated when it exists.

**Comment by outdoor2kode** [comment]
Thanks @pkevan. It makes sense to only show it when it's there then.
