### ISSUE TITLE
Improve search UX

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-developer#40]
While there's some [ideas to improve the search](https://github.com/WordPress/wporg-developer/discussions/14), there probably a few smaller things we can do without replacing it entirely.

- [x]  When typing, the auto-complete dropdown offers exact matches, selecting one of these however just fills the search area, it doesn't submit the form nor does it go to the selected definition.
- [x]  The search button is not immediately obvious, with the search-menu-open icon being larger and more obvious. (This could be just me..)
- [x]  The search icon used on developer is the reverse of the global menu icon direction.

Search clicking (bonus included confusion of where to click) [(mp4)](https://user-images.githubusercontent.com/767313/171106834-8aef4ce7-8ab9-44c8-a51d-bb408292fb57.mov)
<img src="https://user-images.githubusercontent.com/767313/171107964-c3a9b0f5-113c-4cf9-b33e-784df8f20e7d.gif">

Menu icons:
<img width="346" alt="Screen Shot 2022-05-31 at 4 28 55 pm" src="https://user-images.githubusercontent.com/767313/171107227-2989a442-d225-412a-a9b1-1e0ee510d255.png">

**Comment by iandunn** [comment]
> it doesn't submit the form 

➕ , that's always bugged me

> The search button is not immediately obvious

➕ . I'm not sure what a better location would be though; the sidebar?

**Comment by dd32** [comment]
> I'm not sure what a better location would be though; the sidebar?

I'm not sure either. The Global header uses a search button/icon in the same location, but has a focus state that makes it clear the input ends before the icon, which makes it more obvious it might be the button:
<img width="311" alt="Screen Shot 2022-06-01 at 2 17 20 pm" src="https://user-images.githubusercontent.com/767313/171326587-4f1a0670-791f-42de-9bc4-ca02165667f5.png">

**Comment by outdoor2kode** [comment]
Changes made:
* Search Icon is aligned with the global menu icon direction.
* Make the focus state clear - the input ends before the icon.
* Change the placeholder from `Search...` to `Search in Code Reference...`.

Alternative ways to make the search button in the search bar obvious:
a) Always show the search bar and remove the bigger search icon (search-menu-open icon)

![image](https://user-images.githubusercontent.com/18050944/171497821-e0d46f83-cd45-40e3-9a7c-3ed172504543.png)

Or change the bigger search icon to another icon or text, such as:

b) **Arrow up**
![image](https://user-images.githubusercontent.com/18050944/171501318-866341fc-7b97-49f5-9c2d-81ac00f4aa34.png)
![image](https://user-images.githubusercontent.com/18050944/171500963-3a0dc792-6918-4ea8-b247-6714b1d3477c.png)
(I think it's better to retain the search icon when the search bar is collapsed as it's a bit weird to show only an arrow down here. We can change it to arrow up after expanding the search bar.)


c) **Icon + Text** (icon and text is not well aligned here, will be fixed if this option is chosen)
![image](https://user-images.githubusercontent.com/18050944/171501919-f27ac83d-9920-430b-bd5e-ee4d40b8e001.png)

![image](https://user-images.githubusercontent.com/18050944/171502026-d4eee19f-4388-4764-93db-5e99ca4a4d45.png)

Which one is better, a), b), or c)?
Any other thoughts?

**Comment by StevenDufresne** [comment]
Would this control still exist if we use the handbook sidebar? https://github.com/WordPress/wporg-developer/issues/29

<img src="https://d.pr/i/7DcFWn.png" width="300px">

**Comment by iandunn** [comment]
Closing since I think all the issues here have been solved, but please reopen if I missed something.
