### ISSUE TITLE
QA: A couple of more cosmetic issues

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-developer#407]
Did a quick review of [the work in progress](https://developer.wordpress.org/redesign-test/) again just now. It's coming along so well. A few small notes!

## Homepage

Looks good!

## [Handbook](https://developer.wordpress.org/redesign-test/block-editor/)

In general looks good.

Gray-bordered boxes should always have 2px radius, including the collapsed TOC and Chapters.

![2px radius](https://github.com/WordPress/wporg-developer/assets/1204802/9ab1d95d-b9e3-41d8-8e4a-1fd380eab8a7)

Can we also make the whole box clickable, not just the chevron?

Can we make the search field 240px instead of 260px? Ideally a global change. It makes it the same width as the chapters box when that's present:

![search field](https://github.com/WordPress/wporg-developer/assets/1204802/ee5a4328-c75b-4590-abd7-6334b6e6eb65)

Perhaps a content issue, if "Further resources" is bulletted, so should the "Navigating" be:

![navigating](https://github.com/WordPress/wporg-developer/assets/1204802/2796df46-48f5-46dd-bb97-3e0463af8cce)

![further](https://github.com/WordPress/wporg-developer/assets/1204802/60704943-1146-483c-8d00-164a1f0386d5)

## Back to top

Can we show it *only* if you've scrolled at least a little bit?

![back to top](https://github.com/WordPress/wporg-developer/assets/1204802/cb1677db-a346-4aa6-b808-7d918ef0f8cf)

This one is actually kind of important, to the point that *if we can't hide until scroll for launch* we should hide the entire link until we can get that to work. Mostly we want to avoid the above case where you are scrolled to the top, but the link is still showing, quite prominently in some cases.

When scrolled at the top of the page, the TOC is positioned nicely, matching up with the Chapters on the left:

![toc top](https://github.com/WordPress/wporg-developer/assets/1204802/58803743-4819-4d04-b957-a0e1108906dc)

But when you scroll down the page, it sits a bit in the middle, like this:

![toc scrolled](https://github.com/WordPress/wporg-developer/assets/1204802/9149dd29-617e-46f9-98bc-9127b024704d)

Ideally it can *stick* to the top, so that only gets bumped down the page when the header starts "pushing" it, like so:

![sticky](https://github.com/WordPress/wporg-developer/assets/1204802/037f5b19-6e6d-4f66-b901-506a83626b79)

I believe there's a separate issue about also making the chapters list sticky, and chapters would need the same behavior, so you'd have something like this:

![both sticky](https://github.com/WordPress/wporg-developer/assets/1204802/f8952e2c-5483-48af-a23f-3aca1c646cc8)

We can probably flex on what's needed for launch if this is really tricky, but at least the scrolled TOC would be good to tweak if we can.

## [Reference](https://developer.wordpress.org/redesign-test/reference/)

Boxes should have 2px radius:

![rounded](https://github.com/WordPress/wporg-developer/assets/1204802/110d525b-ba9b-4979-a55e-18e191fe8781)

## Notices

The notices are legacy colors and styles:

![legacy notices](https://github.com/WordPress/wporg-developer/assets/1204802/ef5f545f-dcd3-411c-9243-30fa801efc24)

These may be "content", and not feasible to update as part of this effort. But in case they refer to a common CSS class, this is what notices should ideally look like:

![new notices](https://github.com/WordPress/wporg-developer/assets/1204802/60fa5431-1463-4d4d-926a-5538be73c866)

**Comment by adamwoodnz** [comment]
Thanks @jasmussen 

Existing issue for space above ToC now moved back into scope for MVP: https://github.com/WordPress/wporg-mu-plugins/issues/524

New issue for 'Back to top': https://github.com/WordPress/wporg-mu-plugins/issues/521

The others I will address on this issue.

**Comment by adamwoodnz** [comment]
Existing issue for callouts https://github.com/WordPress/wporg-developer/issues/315

**Comment by adamwoodnz** [comment]
> Perhaps a content issue, if "Further resources" is bulletted, so should the "Navigating" be:

Correct, content issue, perhaps you could make this change @ndiego?

Everything else is now done I think, other than the things with existing issues noted above.

> Can we also make the whole box clickable, not just the chevron?

New [issue](https://github.com/WordPress/wporg-mu-plugins/issues/533) for ToC toggle

**Comment by ndiego** [comment]
> Correct, content issue, perhaps you could make this change @ndiego?

Yeah I can take care of this.

**Comment by ndiego** [comment]
> Yeah I can take care of this.

A PR has been created for this here: https://github.com/WordPress/gutenberg/pull/56798
