### ISSUE TITLE
Redirect developer.wordpress.org/playground to wordpress.github.io/wordpress-playground/

### ISSUE THREAD

**Issue by adamziel** [WordPress/wporg-developer#412]
As discussed in https://github.com/WordPress/wordpress-playground/issues/728, developer.wordpress.org/playground  makes more sense as a Playground documentation page than as the overview page it is now. To quote @courtneyr-dev:

> 🌐 Scenario: Seeking Developer Documentation
> 
> Given I am a developer looking for documentation and resources,
> When I navigate to https://developer.wordpress.org/playground,
> Then I expect to find developer documentation and resources directly relevant to my needs.

Once the user-facing content is moved to wordpress.org/playground, let's redirect redirect from the https://developer.wordpress.org/playground page to the documentation site at https://github.com/WordPress/wporg-main-2022/issues/355.

@StevenDufresne https://github.com/WordPress/wordpress-playground/issues/728#issuecomment-1809314830 opening a ticket here to make that happen.

Related:

* https://github.com/WordPress/wporg-main-2022/issues/355

**Comment by StevenDufresne** [comment]
This was done here: https://meta.trac.wordpress.org/changeset/13064
