### ISSUE TITLE
Remove extra <p> tags from the Explanation content

### ISSUE THREAD

**Issue by outdoor2kode** [WordPress/wporg-developer#413]
See discussion https://github.com/WordPress/wporg-developer/pull/411#issuecomment-1828830833 & https://github.com/WordPress/wporg-developer/pull/411#issuecomment-1830416747.

![image](https://github.com/WordPress/wporg-developer/assets/18050944/9078424f-ea42-4dbd-96de-6c57f561540e)

**Comment by adamwoodnz** [comment]
Poor Lighthouse performance tests on https://developer.wordpress.org/redesign-test/reference/classes/wp_query/ suggest these extra p tags are contributing to an excessive DOM size


<img src="https://github.com/WordPress/wporg-developer/assets/1017872/a55db545-c342-4331-ae14-a09eae9c31fb" width="600">

**Comment by adamwoodnz** [comment]
We are also somehow getting multiple links within the More Information section, causing pretty major accessibility issues

![Image](https://github.com/WordPress/wporg-developer/assets/1017872/3b6619a9-fc9b-4375-80c2-e1805848165c)

**Comment by pkevan** [comment]
It looks like the extra `<p>` tags are due to the source html being incorrect, it has them with a `<pre>` inside, which apparently isn't allowed:

```
<p><pre class="wp-block-code"><code lang="php" class="language-php ">$query = new WP_Query( array( 'author' =&gt; 123 ) );</code></pre></p>
```

I couldn't figure out where the content comes from but will look further.

**Comment by pkevan** [comment]
> somehow getting multiple links

That is in the source HTML 😄 , so probably an issue parsing the content.

**Comment by pkevan** [comment]
Perhaps the extra `<p>` tags are from `wpautop`, since they don't exist in the source: https://developer.wordpress.org/redesign-test/wp-admin/post.php?post=149467&action=edit

**Comment by pkevan** [comment]
Looks like you can get around the autop thing by removing any spacing between the code block and the text above - that might be more work 🤷
