### ISSUE TITLE
Homepage font sizes and weights

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#418]
In testing the redesign for the last few weeks, I have found that I consistently have a hard time reading the card headings on the homepage at a quick glance. It might be my vision, but I often have to stop and focus on each one. I think this because the font-size is small and the headings are heavily bolded (700).

In looking into this, I realized we are also using different font weights across similar heading levels. Therefore, I messed around in the browser and came up with the following. 

I don't think this is high priority, or if anything necessarily needs to change, but wanted to share this exploration.

| Proposed | Current |
|-|-|
|![developer wordpress org_redesign-test_](https://github.com/WordPress/wporg-developer/assets/4832319/b129bc00-3440-440f-a9d7-125350fe5d5e)|![developer wordpress org_redesign-test_ (2)](https://github.com/WordPress/wporg-developer/assets/4832319/35294d56-20cc-4017-8d74-ee329d36a2e7)|

Changes:

- All `h2` have font-size `var(--wp-preset--font-size--large)` (20px) and font-weight `var(--wp--custom--heading--typography--font-weight)` (600) - This change only impacts the `h2` in the black footer
- All `h3` have font-size `var(--wp-preset--font-size--normal)` (16px) and font-weight `var(--wp--custom--heading--typography--font-weight)` (600)
- The titles of each post are updated to match the styling of `h3`
- The white descriptive text below the headings in the black footer have font-size `var(--wp-preset--font-size--small)`

**Comment by adamwoodnz** [comment]
@WordPress/meta-design thoughts please?

**Comment by jasmussen** [comment]
Looks good to me, though I'd appreciate a sanity check by @fcoveram.

Note that this will need some Figma updates for subsequent redesigns in the Learn category, because we want changes like these to propogate across every shared design element across the whole site.

**Comment by fcoveram** [comment]
It looks good to me. And Joen is right about the update. Saving this change in my notes as input for future mockups.
