### ISSUE TITLE
Add a link to LearnWP on Developer 

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/wporg-developer#431]
At the end of the Developer Site landing page, I suggest it could be helpful to add a text link to https://learn.wordpress.org/. This could provide another source of information to folks who may land on this page, but are not development-focused. (it is called out in the footer but as a list of links, not directly)

Maybe something to the effect of:

`Looking to learn more about how to use WordPress? Check out [learn.wordpress.org](https://learn.wordpress.org/) for more resources, including user-focused tutorials.`

Note: Could also be in a footer. (We could also link to the Developer site from Learn, though that may already be in place.)

**Comment by adamwoodnz** [comment]
Calling @WordPress/meta-design, thoughts?

**Comment by fcoveram** [comment]
I like this idea; it makes total sense to me.

I wonder if we should replace the two links in the "Related" section in the dark banner with a single link to Learn. Both links take you to handbook pages that are also linked from the "Core Contributor Handbook" one on the left. I might be missing context, but at first sight, this looks unnecessarily redundant.

![Screenshot of Developers landing page, related links section](https://github.com/WordPress/wporg-developer/assets/895819/10be2f63-2c18-4162-8935-04ce8b3f27dc)

What do you think? Pinging @ndiego and @StevenDufresne as they might have more context.

---

In the case of Learn, we can address it similarly. The latest design has a spot for it on the banner's far right.

![Screenshot of Learn landing page, related links section](https://github.com/WordPress/wporg-developer/assets/895819/190b01a8-9e2f-4f39-94aa-c37fdf07a22b)

**Comment by ndiego** [comment]
Yeah I think this is a great idea. The Related links do feel redundant. They were brought over from the current landing page, but highlighting is likely more impactful here.
