### ISSUE TITLE
"Improve it on GitHub" links don't go anywhere if the user is logged out

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#438]
The "Improve it on GitHub" links in the Block Editor Handbook are not correctly linking to the respective GitHub pages (https://developer.wordpress.org/block-editor/). 

<img width="346" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/6abcc165-f5ca-46d5-a02a-8c1f2d89f86e">

**Comment by adamwoodnz** [comment]
It takes me to a page to fork Gutenberg, I didn't think about it too much and assumed it was expected.

![Image](https://github.com/WordPress/wporg-developer/assets/1017872/5170840f-7fd4-4894-83a5-053cf4e86c98)

Same for you? Would we need to update the repo settings if we wanted people to be able to edit?

**Comment by ndiego** [comment]
Hmm, on [this page](https://developer.wordpress.org/block-editor/getting-started/devenv/) the link just takes me to: https://developer.wordpress.org/block-editor/getting-started/devenv/. 

As for the GitHub landing page, that is fine for now. It was how it worked before. Not ideal, but feature parity.

**Comment by outdoor2kode** [comment]
It directly takes me to https://github.com/WordPress/gutenberg/edit/trunk/docs/README.md because I've forked the repo before.

![image](https://github.com/WordPress/wporg-developer/assets/18050944/97864c8b-7900-469f-b9fc-41d3db3dfbec)

**Comment by ndiego** [comment]
I figured it out! The link goes to GitHub if you are logged in. If not, it just redirects you to the page you are on.

**Comment by ndiego** [comment]
Yeah, the same thing happens in the Rest API Handbook if logged out.

**Comment by bacoords** [comment]
I'll just note that if you're logged in but don't have permissions to edit the site, the GitHub link still doesn't show up- I'm assuming because of how you're using `get_edit_post_link()`.

**Comment by ndiego** [comment]
> I'll just note that if you're logged in but don't have permissions to edit the site, the GitHub link still doesn't show up- I'm assuming because of how you're using get_edit_post_link().

Good catch, thanks for reporting Brian! This is a high-priority fix for next week.
