### ISSUE TITLE
The API reference is empty

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#439]
The API reference section on https://developer.wordpress.org/reference/ is empty

<img width="908" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/898f4369-618b-42b0-b886-437fdc47cbb9">

**Comment by adamwoodnz** [comment]
Fixed by https://github.com/WordPress/wporg-developer/commit/5ef6bb6b670a0c8a91a947a1ed8b114e2452dc37
