### ISSUE TITLE
Improve Open Graph properties throughout Developer Resources

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#442]
Right now, and in the previous design, the Open Graph properties for each individual page in Developer Resources are all the same, and there is no thumbnail image. We should improve this post-launch.

| [Example 1](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeveloper.wordpress.org%2Fblock-editor%2F) | [Example 2](https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fdeveloper.wordpress.org%2Fthemes%2F) |
|-|-|
|<img width="1248" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/b61a5469-04b8-46f9-bf8d-dc5278b6bb2d">|<img width="1232" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/b9ae5c16-9cf9-4702-aa42-811b8ae7ce24">|

cc @fcoveram @thetinyl for thoughts

**Comment by thetinyl** [comment]
> the Open Graph properties for each individual page in Developer Resources are all the same

Oh dear. Could these be dynamically generated based on the page content? (Images included in this ask.)

**Comment by fcoveram** [comment]
Here is an idea based on the visuals made for other sections

![Developers social-image](https://github.com/WordPress/wporg-developer/assets/895819/9be61140-20a8-4e7a-9402-6c2446e0d1c1)

**Comment by thetinyl** [comment]
@fcoveram Three things stick out to me about the thumbnail:

1. I appreciate the consistency in the visual language. It's a subtle nice touch. 
2. I think we need to add WordPress in the subcopy to be consistent with the other thumbnails (both Showcase and Events have it), but also to be just a little more obvious that this is WP. For some folks, they're not going to read anything beyond the image text as they skim their feeds, and the dot motif isn't enough to signal "WordPress" on its own. Could be as simple as: **The freedom to build with WordPress**
3. This is a question for the target audience of Devs or Dev-minded folk: Is "Developers" compelling enough to get you to follow the link/read the rest of the OpenGraph info? To me, this feels like it's missing the hook and I'd want it to be consistent with the title of the section (Developer Resources). But I acknowledge it'll exist with additional context and fits the one-word pattern of the other sections. @ndiego Thoughts?

**Comment by ndiego** [comment]
Yeah, ideally, it would be great to include "Resources" and we also need "WordPress" in there somewhere. I like "The freedom to build with WordPress" 🙌

**Comment by fcoveram** [comment]
Great feedback. Here is an idea with the feedback applied.

![Developers social-image 021](https://github.com/WordPress/wporg-developer/assets/895819/a942fae6-20ee-481a-b2f8-aeaa199a79ee)

**Comment by thetinyl** [comment]
@fcoveram Nice! Minor copy edit for you: drop the 's' from 'Developers' ---> 'Developer Resources'

**Comment by fcoveram** [comment]
Oh you're right 😅 I updated the comment above with the new image. Sorry!

**Comment by ndiego** [comment]
Lookin good to me!

**Comment by ndiego** [comment]
Thanks everyone!

**Comment by ryelle** [comment]
It was reported that this isn't showing up on twitter, because we don't have a `twitter:image` tag (thanks @bph!). Reopening to track fixing that.
