### ISSUE TITLE
Make "Chapters" and "In this article" buttons fully clickable 

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#443]
On mobile devices, the Chapter list and TOC collapse down. You can then click on the little carrot icon to expand the lists. I found the clickable area to be a bit small (red) and it would be great if the entire area (green) was clickable. 

<img width="400" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/dfdaa866-87fd-4f74-938d-fe708f03fd47">

**Comment by adamwoodnz** [comment]
Thanks for raising, duplicate of https://github.com/WordPress/wporg-developer/issues/434
