### ISSUE TITLE
Parameters list HTML is a little broken on `WP_Query::parse_query`

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-developer#45]
See https://developer.wordpress.org/reference/classes/WP_Query/parse_query/ — when the list in `orderby` is output, the indentation afterwards is off. 

See how the parameters are indented twice, until after `orderby`, when they're no longer indented enough and now they have bullets:

<details>
<summary>Very long screenshot of the params list</summary>

![Screen Shot 2022-05-31 at 18 58 18-fullpage](https://user-images.githubusercontent.com/541093/171298145-f4328588-73dc-419a-81b1-050c5421cdc3.png)

</details>

**Comment by dd32** [comment]
Responsible code for lists in params:
https://github.com/WordPress/wporg-developer/blob/trunk/source/wp-content/themes/wporg-developer/inc/formatting.php#L479-L496

Looks like we don't support lists within lists, `Does not handle nesting of lists.`.

**Comment by dd32** [comment]
Interestingly, there's also some issues in the parsing of some of the fields.

For `$fields` the final line of the documentaion, `Default ''` is missing:
https://github.com/WordPress/wordpress-develop/blob/6.0/src/wp-includes/class-wp-query.php#L656-L661

I've done more digging, and the way the PHPDoc source is imported causes some things to be lost.

For example, the `orderby` section imported lacks the newlines ([They're stripped out](https://github.com/WordPress/phpdoc-parser/blob/master/lib/runner.php#L136-L175)):
```
@type string\|array    $orderby                 Sort retrieved posts by parameter. One or more options may be passed.                                                    To use 'meta_value', or 'meta_value_num', 'meta_key=keyname' must be                                                    also be defined. To sort by a specific `$meta_query` clause, use that                                                    clause's array key. Accepts:                                                    - 'none'                                                    - 'name'                                                    - 'author'                                                    - 'date'                                                    - 'title'                                                    - 'modified'                                                    - 'menu_order'                                                    - 'parent'                                                    - 'ID'                                                    - 'rand'                                                    - 'relevance'                                                    - 'RAND(x)' (where 'x' is an integer seed value)                                                    - 'comment_count'                                                    - 'meta_value'                                                    - 'meta_value_num'                                                    - 'post__in'                                                    - 'post_name__in'                                                    - 'post_parent__in'                                                    - The array keys of `$meta_query`.                                                    Default is 'date', except when a search is being performed, when                                                    the default is 'relevance'.
```

Simply keeping newlines isn't entirely an option, but the loss of the newlines has other effects. See incoming PR.
