### ISSUE TITLE
The "Last updated" date is incorrect in Handbooks that source their content from GitHub

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#456]
In handbooks where the content lives in GitHub, the "Last updated" displays the last time the content was synced from GitHub. The [Block Editor Handbook](https://developer.wordpress.org/block-editor/getting-started/quick-start-guide/) is a good example. 

The image below is from the [Quick Start Guide](https://developer.wordpress.org/block-editor/getting-started/quick-start-guide/). The actual content was last updated on 11/19, but the date is showing today.

<img width="509" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/ac615162-8124-41de-a5a7-7b7348e71db5">

**Comment by adamwoodnz** [comment]
We had a previous [issue](https://github.com/WordPress/wporg-developer/issues/345) to remove this info for the Block Editor handbook (although this should probably apply to all GitHub handbooks), but there must have been a regression and it has been added back. Do we want to try to get the actual last edit date from GitHub, or just remove it again?

**Comment by ndiego** [comment]
It would be great to get the actual date if possible. But perhaps we just remove it for the time being while an alternative implementation is explored? I don't know how hard it would be to get the actual date.

**Comment by adamwoodnz** [comment]
> But perhaps we just remove it for the time being while an alternative implementation is explored? I don't know how hard it would be to get the actual date.

Yeah I think this sounds like a plan. Looks like we can [query for commits using the GitHub API](https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-commits-on-a-repository), and get the date for the last commit.

**Comment by StevenDufresne** [comment]
A couple questions to help identify the solution:
- Why does that matter to the user who assumes this is the canonical information source?
- Does the sync update all dates or only the documents that were modified?

**Comment by ndiego** [comment]
> Why does that matter to the user who assumes this is the canonical information source?

Since we have a lot of outdated docs (this is being worked on), the fact that the "Last updated" date shows the current date is quite misleading. 

> Does the sync update all dates or only the documents that were modified?

To my knowledge, the entire Handbook is synced every 15 min, so the "Last updated" date always shows the current date. Another option would be to only sync if a change is detected, but not sure what's the easiest solution.

**Comment by adamwoodnz** [comment]
> Does the sync update all dates or only the documents that were modified?

> Another option would be to only sync if a change is detected, but not sure what's the easiest solution.

From what I can see [2 cron jobs run every 15 mins](https://github.com/WordPress/wporg-developer/blob/trunk/source/wp-content/themes/wporg-developer-2023/inc/import-docs.php#L163), [the first updates the post meta](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-markdown/inc/class-importer.php#L107), [the second updates the post content from markdown source](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-markdown/inc/class-importer.php#L301). Neither checks for whether a post has been updated since the last import.

So we could make a GitHub API call here to get the last commit date and compare with the previous date, and only run the update if there is a newer commit. I'm concerned that the volume of requests might cause rate limiting though. It would be hundreds of pages in a burst every 15 mins. Another option could be to get the last commit date on page load, which would spread the API requests, but could lead to slower page load times. A final option could be to do it on the frontend which wouldn't block the page load.

Thoughts?

cc @dd32 as I think you've got experience with this

**Comment by dd32** [comment]
> From what I can see [2 cron jobs run every 15 mins](https://github.com/WordPress/wporg-developer/blob/trunk/source/wp-content/themes/wporg-developer-2023/inc/import-docs.php#L163), [the first updates the post meta](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-markdown/inc/class-importer.php#L107), [the second updates the post content from markdown source](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-markdown/inc/class-importer.php#L301). Neither checks for whether a post has been updated since the last import.

There is a check in there, specifically the 304 + etag check in `update_post_from_markdown_source()`, which appears to work, avoiding `wp_update_post()` unless the source has changed.

That then causes it to update it from the manifest source.
Using https://developer.wordpress.org/block-editor/getting-started/quick-start-guide/ as an example, which is ID 150150, running the cron event results in this:

```
$ wp @developer cavalcade run 12316181
...
Updated 150150 from manifest source
No updates for 150150
...
```

That means it's updating from the manifest source, not the markdown.

The manifest must therefor be [defining one of the other post fields, causing it to update the post every time](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-markdown/inc/class-importer.php?marks=336-339#L330).

After https://github.com/WordPress/wordpress.org/commit/a1c3f68199e4e39a7d9e95fdee70dbce2627f6c3 this now results in this:

```
$ wp @developer cavalcade run 12316181
...
No updates for 150150
...
```

Many articles will still have a last-modified date of today however, as none of this changes the post-modified dates of the handbooks back to the "correct" dates, as WordPress really doesn't like you specifying the `post_modified` fields for posts :)

There's probably still room here to query for the last-modified of the pages in the markdown update however, as due to the etag/304 checks, the code branch will only be hit when there's actually a change in the page.  but again, you can't pass `post_modifed` to `wp_update_post()`, without some extra filters to allow it to happen.

**Comment by adamwoodnz** [comment]
Thanks Dion 🚀 

So are we happy for dates to organically be updated over time from now, or do we need it to be more accurate?

I think the most misleading thing would be for the last updated date to always be today, which we have now stopped.

**Comment by dd32** [comment]
> I think the most misleading thing would be for the last updated date to always be today, which we have now stopped.

I think it's worth correcting it, if the last-updated date is going to be exposed in the design again. 

This part of my last comment:

> There's probably still room here to query for the last-modified of the pages in the markdown update

is probably partly needed to be implemented to correct the dates of existing pages. 

Unfortunately, the easiest way to achieve this is probably to switch from using `raw.githubcontent` to using the GitHub API, which would likely need to use authenticated calls.. 

Current only: https://raw.githubusercontent.com/WordPress/gutenberg/trunk/docs/getting-started/quick-start-guide.md
API endpoint that has the `Content` and `Last Modified` date: https://api.github.com/repos/WordPress/gutenberg/contents/docs/getting-started/quick-start-guide.md [(docs)](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28)

There's some downsides of using the github api though:
 - Either needs to be setup as a GitHub App, or it'll be using low rate limits
 - Local development benefits from the current non-API method, as it just works without rate limits

After typing all this out, here's my thoughts in order of preference...
 - Leave it as-is.
 - Leave the importer as-is, run a once-off script to correct.
 - Fetch the API if possible, unauthenticated, to get the last-mod date, if possible, but know it'll be limited to the first 60 requests
 - Require a GitHub APP to be setup to import handbooks, even in local environments

**Comment by dd32** [comment]
> Leave the importer as-is, run a once-off script to correct.

I ended up doing this, here's the CLI script I ran to do this.

```php
<?php
$_SERVER['REQUEST_URI'] = '/';
$_SERVER['HTTP_HOST'] = 'developer.wordpress.org';
include 'wp-load.php';

// Find the problematic items..
$items = $wpdb->get_results(
	"SELECT p.ID, p.post_modified, pm.meta_value
		FROM $wpdb->posts p
		JOIN $wpdb->postmeta pm ON p.ID = pm.post_id AND pm.meta_key = 'wporg_markdown_source'
	WHERE p.post_status = 'publish' AND p.post_modified_gmt >= '2024-01-01'"
);

// Allow post_modified to be modified
add_filter(
	'wp_insert_post_data',
	function( $data, $postarr ) {
		$data['post_modified']    = $postarr['post_modified']      ?? $data['post_modified'];
		$data['post_modified_gmt'] = $postarr['post_modified_gmt'] ?? $data['post_modified_gmt'];

		return $data;
	},
	10,
	2
);

foreach ( $items as $item ) {
	$api_path = $item->meta_value;
	$api_path = preg_replace( '!^https://raw.githubusercontent.com/([^/]+/[^/]+)/[^/]+/(.+)$!i', '/repos/$1/commits?path=$2', $api_path );
	$api_path = preg_replace( '!^https://github.com/([^/]+/[^/]+)/blob/[^/]+/(.+)$!i', '/repos/$1/commits?path=$2', $api_path );

	// Get the last commit date, use the `gh` cli for auth'd requests due to low rate limits.
	$output = trim( `gh api --cache 1h $api_path | jq -r .[0].commit.author.date` );

	$last_mod = gmdate( 'Y-m-d H:i:s', strtotime( $output ) );

	echo "{$item->ID} {$item->post_modified} {$last_mod} --- {$api_path}\n";

	// Update the dates.
	wp_update_post( [
		'ID'            => $item->ID,
		'post_modified' => $last_mod,
		'post_modified_gmt' => $last_mod,
	] );

}
```

**Comment by adamwoodnz** [comment]
Awesome work! I'll create a PR to display the date again asap.

**Comment by adamwoodnz** [comment]
I've now shown the field again. Checked the GitHub handbooks and all look good except [Rest API](https://developer.wordpress.org/rest-api/), where the Last Updated date is always Dec 14 2023. That doesn't match GitHub (eg. https://github.com/WP-API/docs/blob/master/index.md was last edited 6 Aug 2022), seems we skipped it, investigating...

**Comment by dd32** [comment]
Looking at the dates, I only reprocessed recently dated ones, but I'm guessing these pages were re-created at a previous time point.

Looking at the pages for that specific handbook:
```
ID	 post_modified		 lastCommitDate		Commit API endpoint
25435 	 2023-12-14 20:17:22 	 2020-12-05 21:04:18 	--- /repos/WP-API/docs/commits?path=changelog.md
25312 	 2023-12-14 20:15:57 	 2020-03-31 13:24:36 	--- /repos/WP-API/docs/commits?path=extending-the-rest-api.md
22832 	 2023-12-14 20:14:25 	 2022-08-05 16:29:19 	--- /repos/WP-API/docs/commits?path=index.md
23078 	 2023-12-14 20:16:13 	 2023-02-08 18:20:16 	--- /repos/WP-API/docs/commits?path=reference.md
22846 	 2023-12-14 20:16:49 	 2021-07-09 23:21:13 	--- /repos/WP-API/docs/commits?path=requests.md
24962 	 2023-12-14 20:15:45 	 2020-03-31 13:24:36 	--- /repos/WP-API/docs/commits?path=using-the-rest-api.md
25388 	 2023-08-31 19:10:32 	 2021-09-05 21:01:26 	--- /repos/WP-API/docs/commits?path=extending-the-rest-api/adding-custom-endpoints.md
23089 	 2023-04-25 14:55:35 	 2023-04-25 14:45:32 	--- /repos/WP-API/docs/commits?path=extending-the-rest-api/adding-rest-api-support-for-custom-content-types.md
22844 	 2023-01-31 17:40:33 	 2023-01-31 17:39:06 	--- /repos/WP-API/docs/commits?path=extending-the-rest-api/controller-classes.md
23185 	 2023-12-14 20:17:04 	 2023-04-25 14:45:32 	--- /repos/WP-API/docs/commits?path=glossary.md
25288 	 2020-08-09 06:04:44 	 2020-08-09 05:56:16 	--- /repos/WP-API/docs/commits?path=extending-the-rest-api/modifying-responses.md
22842 	 2023-02-16 07:10:33 	 2022-07-29 17:19:32 	--- /repos/WP-API/docs/commits?path=extending-the-rest-api/routes-and-endpoints.md
22852 	 2023-02-16 04:10:32 	 2023-02-16 03:58:06 	--- /repos/WP-API/docs/commits?path=extending-the-rest-api/schema.md
23122 	 2023-08-24 20:55:36 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/categories.md
23126 	 2023-08-24 20:55:37 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/comments.md
23116 	 2023-08-24 20:55:36 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/media.md
28916 	 2023-08-24 20:55:32 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/page-revisions.md
23105 	 2023-08-24 20:55:36 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/pages.md
23100 	 2023-08-24 20:55:37 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/post-revisions.md
23124 	 2023-08-24 20:55:37 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/post-statuses.md
23120 	 2023-08-24 20:55:36 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/post-types.md
23098 	 2023-08-24 20:55:37 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/posts.md
23113 	 2023-08-24 20:55:35 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/settings.md
23127 	 2023-08-24 20:55:35 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/tags.md
23141 	 2023-08-24 20:55:35 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/taxonomies.md
23115 	 2023-08-24 20:55:35 	 2023-08-24 20:38:10 	--- /repos/WP-API/docs/commits?path=reference/users.md
22840 	 2023-04-25 14:55:36 	 2023-04-25 14:45:32 	--- /repos/WP-API/docs/commits?path=using-the-rest-api/authentication.md
24919 	 2023-02-16 07:10:30 	 2021-04-06 15:31:06 	--- /repos/WP-API/docs/commits?path=using-the-rest-api/backbone-javascript-client.md
24963 	 2023-12-04 20:40:32 	 2023-12-04 20:30:42 	--- /repos/WP-API/docs/commits?path=using-the-rest-api/client-libraries.md
23085 	 2023-01-17 17:10:32 	 2023-01-17 16:55:54 	--- /repos/WP-API/docs/commits?path=using-the-rest-api/discovery.md
25329 	 2023-12-14 20:15:35 	 2020-10-27 18:32:33 	--- /repos/WP-API/docs/commits?path=frequently-asked-questions.md
23167 	 2020-03-30 15:43:31 	 2020-03-30 15:29:31 	--- /repos/WP-API/docs/commits?path=using-the-rest-api/global-parameters.md
23145 	 2023-08-24 19:40:33 	 2023-08-12 06:52:42 	--- /repos/WP-API/docs/commits?path=using-the-rest-api/linking-and-embedding.md
23077 	 2019-10-21 17:43:36 	 2018-01-17 21:54:13 	--- /repos/WP-API/docs/commits?path=using-the-rest-api/pagination.md
```

This probably means that we probably should do something to figure out the last-modified dates, as when importing a handbook for the first time, the last-modified will always be `time()` even if the handbook source has been stale for a month.

**Comment by dd32** [comment]
For the meantime, the above script has been run for ALL github imported pages, not just the ones altered recently. That's reset the modified date to the same as the references. 

I guess we should look at importing those modified dates with the content after all.
