### ISSUE TITLE
Handbook: Import the post_modified from last Github commit date

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-developer#464]
Per #456 the last modified date of github-imported handbooks can be incorrect.

While the above issue has been closed via a once-off fix, we should move forward with querying the last commit upon markdown import, such that the dates (which are now prominently displayed) are accurate.

To make it work with standalone environments, as well as production, we can use a GitHub App if available and fall back to unauthenticated API requests if not. That should likely be enough to mostly-work™ for local testing, while working perfectly in production.

Note: The markdown importer is not contained within this repo, but this is the primary place it's used and this bug is visible. The source is here: https://github.com/WordPress/wordpress.org/tree/trunk/wordpress.org/public_html/wp-content/plugins/wporg-markdown

**Comment by outdoor2kode** [comment]
For some unknown reason, the deprecated PR link in the development section on the right side of this page is unable to be removed, and the attempt to remove them has messed up the page.. So closing this issue and opening another one to keep it clean. https://github.com/WordPress/wporg-developer/issues/505
