### ISSUE TITLE
Blockquote notices break on the search results page

### ISSUE THREAD

**Issue by carolinan** [WordPress/wporg-developer#465]
When an article contains a blockquote, there is a problem with how these are presented on the search results page.
The excerpt includes the HTML for the notice, which interrupts the text and breaks the layout.

[Example link](https://developer.wordpress.org/block-editor/?s=deprecation)

Screenshot:
<img width="1219" alt="Search results with broken excerpt" src="https://github.com/WordPress/wporg-developer/assets/7422055/19318337-985e-4a98-b7a8-c4523dc9f59d">

Markup:

```
<div class="wp-block-post-excerpt">
<p class="wp-block-post-excerpt__excerpt">
&gt; This page provides a comprehensive guide to the principles and usage of the Deprecation API. For an introduction check out the 
</p><div class="wp-block-wporg-notice is-tip-notice">
<div class="wp-block-wporg-notice__icon"></div>
<div class="wp-block-wporg-notice__content"></div></div>
(https://developer.wordpress.org/news/2023/03/block-deprecation-a-tutorial/) which can be found on the [Developer Blog](https://developer.wordpress.org/news/). <p></p></div>
```

Expected:

This page provides a comprehensive guide to the principles and usage of the Deprecation API. For an introduction check out the [tutorial on the basics of block deprecation](https://developer.wordpress.org/news/2023/03/block-deprecation-a-tutorial/) which can be found on the [Developer Blog](https://developer.wordpress.org/news/).

**Comment by ndiego** [comment]
Further down that [example link](https://developer.wordpress.org/block-editor/?s=deprecation) page, it is also displaying the markdown: 
<img width="1256" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/72497d9c-bf4a-4746-b678-c4f1a7f64691">

**Comment by ryelle** [comment]
Looks like this is because the content in that search is `For an introduction check out the [tutorial on the basics of block deprecation](https…`, and that `[tutorial` is triggering the notice shortcode.
