### ISSUE TITLE
Changelog/improve this links shown on code reference pages

### ISSUE THREAD

**Issue by adamwoodnz** [WordPress/wporg-developer#473]
> I am seeing the changelog/improve this links on code reference pages (like https://developer.wordpress.org/reference/functions/block_has_support/), but I think that's true on production to. Is that intentional?

The designs show no meta info at all on code reference.

_Originally posted by @adamwoodnz in https://github.com/WordPress/wporg-mu-plugins/issues/558#issuecomment-1892835013_

**Comment by ryelle** [comment]
Fixed by #472
