### ISSUE TITLE
Code examples parsed from description aren't syntax highlighted

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-developer#48]
This applies both on the old site and also in the new highlighter branch #44.

See https://developer.wordpress.org/reference/functions/apply_filters/
<img width="989" alt="Screen Shot 2022-06-01 at 3 16 50 pm" src="https://user-images.githubusercontent.com/7200686/171332889-6ae3cb14-c336-4a7e-a0cc-3db0b9442848.png">

The `Example usage` block isn't highlighted. I'm not sure if that's a data problem in the content, or if highlighting is sometimes not applied to code in the description. Note that this text comes from the parsed description, not an Explanation CPT.

**Comment by iandunn** [comment]
Could be related to [the absence of the `<?php` tag](https://github.com/WordPress/wporg-developer/pull/44#issuecomment-1143947766).

**Comment by tellyworth** [comment]
Yep it probably is. I'll make this as a Duplicate of #52 .

**Comment by ryelle** [comment]
This isn't related to #52 — that one is just for the Explanations, but this likely happens in all the places that use the code block.

**Comment by ryelle** [comment]
… actually, this is yet another edge case for the syntax highlighter, this is just code embedded in the description. It's also not highlighted [on production](https://developer.wordpress.org/reference/functions/apply_filters/)

![](https://user-images.githubusercontent.com/541093/171742546-56b6d1ad-c15f-4a7b-9d10-bddef01a4b5e.png)
