### ISSUE TITLE
Handbook menus expands/contracts on each page load

### ISSUE THREAD

**Issue by pkevan** [WordPress/wporg-developer#483]
https://github.com/WordPress/wporg-developer/assets/2290623/5f94cd26-fcba-49ee-97ec-8767c542fd94

On each page load, the menu contracts and expands, even when staying within the same sub-menu. Unsure how easy this would be to fix, but creates a non-ideal user experience.

**Comment by ryelle** [comment]
This is a duplicate of https://github.com/WordPress/wporg-developer/issues/255 (FOUC = "flash of unstyled content").
