### ISSUE TITLE
Improve layout consistency between pages with left-hand sidebar and those without

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#484]
This issue comes from a discussion in [WordPress Slack](https://wordpress.slack.com/archives/C04U953K77A/p1704827379423609), but I wanted to expand on it here. On the [Developer Resources](https://developer.wordpress.org/) site, we generally have two layouts. One with a left-hand sidebar for the "Chapters" list and a layout without this sidebar. 

**Current design:**
| A: Layout with sidebar ([link](https://developer.wordpress.org/block-editor/)) | B: Layout without a sidebar ([link](https://developer.wordpress.org/cli/commands/)) |
|-|-|
|<img width="1911" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/77bb42eb-5429-4bc8-9b09-b1c840f11c1d">|<img width="1914" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/140e4e27-74b7-4003-8b50-31fef4a4634f">|

A few things to note here:

- On large screens, the search field is not aligned under the breadcrumbs in design B
- The content area width is smaller in design B (this was the original discussion in [Slack](https://wordpress.slack.com/archives/C04U953K77A/p1704827379423609)), `960px` versus `680px`. 

To improve consistency, I recommend that we set the content width on all internal pages with specific width, perhaps `960px` or maybe a tad smaller. I'll leave that to Design.

In design B, make sure the search field is in the same spot (positioned below the breadcrumbs), and update the layout so it's exactly the same as design A, but just without the "Chapters" list. Also the `h1` in design B is slightly smaller than design A. 

The result would probably look like this. 

**Proposed design:**
| A: Layout with sidebar ([link](https://developer.wordpress.org/block-editor/)) | B: Layout without a sidebar ([link](https://developer.wordpress.org/cli/commands/)) |
|-|-|
|<img width="1911" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/77bb42eb-5429-4bc8-9b09-b1c840f11c1d">|<img width="1912" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/5f36e649-e891-4b8c-afed-fcb440925f8f">|

I also want to note that where we land on this will impact the upcoming redesign of [Documentation](https://wordpress.org/documentation/article/administer-your-blog/), where most pages use the current B layout.

**Comment by ryelle** [comment]
Great idea!

Just to clarify (it looks like this is true from the slack convo), this applies to the code reference pages too — they use "layout B".

![Screen Shot 2024-01-24 at 11 27 05](https://github.com/WordPress/wporg-developer/assets/541093/123cc8e9-9d70-4f20-a764-92eac94450cd)

We'll still need to add a switch for medium-sized screens, otherwise we'll end up with something like this:

![Screen Shot 2024-01-24 at 11 29 00](https://github.com/WordPress/wporg-developer/assets/541093/a2e3eaa7-3ffc-41a1-93ef-8021a9364498)

**Comment by ndiego** [comment]
> this applies to the code reference pages too

Yup, I should have used that as the screenshot. Basically, all pages that have design B should be updated, IMO. 

> We'll still need to add a switch for medium-sized screens, otherwise we'll end up with something like this:

Yeah 100%, there is some nuance here. I am also wondering if we might add a "Chapters" list to some of these pages. For example, the code reference pages could have a simple list that navigates you to:

- [Functions](https://developer.wordpress.org/reference/functions/)
- [Hooks](https://developer.wordpress.org/reference/hooks/)
- [Classes](https://developer.wordpress.org/reference/classes/)
- [Methods](https://developer.wordpress.org/reference/methods/)

Also, from a structural standpoint, I don't think we need to add an empty column to support this layout. In some quick browser hacking, I think we can just update the content width to `960px` and remove some `alignwide` settings on Group blocks.

**Comment by outdoor2kode** [comment]
> We'll still need to add a switch for medium-sized screens, otherwise we'll end up with something like this:

Does this situation happen? When I see the ToC become a Dropdown, the content always seems to already be pushed to the very left.

![search](https://github.com/WordPress/wporg-developer/assets/18050944/69c59968-855e-42d7-a959-3122cdaccfae)

**Comment by ryelle** [comment]
> Does this situation happen?

Not currently, but if we just dropped the 3-column layout onto the current 2-col pages, with an empty sidebar, it would.

**Comment by ndiego** [comment]
> Not currently, but if we just dropped the 3-column layout onto the current 2-col pages, with an empty sidebar, it would.

I haven't experimented with it yet, but I think it could be designed in a way to avoid this. If the container is set to a content width of `960px` and you remove the `alignwide` on the surrounding container, it should just collapse naturally. Some tweaks to the TOC would be needed, but it might be just setting `right: 0`.

**Comment by ryelle** [comment]
> I haven't experimented with it yet, but I think it could be designed in a way to avoid this

Absolutely, I just noticed it while i was playing around with the idea and wanted to make sure it got addressed by whoever picks this up.

Have we decided it's worth trying, or do we still need design feedback?

**Comment by ndiego** [comment]
@fcoveram @marko-srb what do you both think?

**Comment by mkismy** [comment]
I wonder if we can have consistency with the documentation articles too.

|||
|:--|:--|
|![image](https://github.com/WordPress/wporg-developer/assets/8445575/6349dd96-2553-43f5-90cd-1c7f5fcf0f5a)|![image](https://github.com/WordPress/wporg-developer/assets/8445575/127e57bc-86f7-4696-9556-ad33d022815c)|

**Comment by ndiego** [comment]
@mkismy absolutely. We are actually about to kick off another redesign of Documentation that will incorporate many of the improvements that have been made recently to the Developer Resources site.

**Comment by fcoveram** [comment]
The [design proposed](https://github.com/WordPress/wporg-developer/issues/484#issue-2098629171) in the initial comment and centering the main content area sound like great solutions to me. I don't have further comments so go ahead.

**Comment by adamwoodnz** [comment]
The linked PR is almost ready with updated layouts for CLI Commands and the single layouts.

> To improve consistency, I recommend that we set the content width on all internal pages with specific width, perhaps `960px` or maybe a tad smaller. I'll leave that to Design.
> 
> In design B, make sure the search field is in the same spot (positioned below the breadcrumbs), and update the layout so it's exactly the same as design A, but just without the "Chapters" list. Also the `h1` in design B is slightly smaller than design A.

There are other layouts which are outliers with different content widths and search aligned with the content, eg. 
https://developer.wordpress.org/reference/
https://developer.wordpress.org/reference/hooks/
https://developer.wordpress.org/?s=query
https://developer.wordpress.org/reference/since/6.4.0/

### Screenshots

| Current | 960px with realigned search |
|-|-|
| ![developer wordpress org_reference_since_6 4 0_(1 1920x1080)](https://github.com/WordPress/wporg-developer/assets/1017872/5f6c9111-0fd9-4f80-bf25-7d34f3d86b42) | ![localhost_8888_reference_since_6 4 0_(1 1920x1080) (1)](https://github.com/WordPress/wporg-developer/assets/1017872/eea5dd85-80f1-425a-9af5-5f9eb2f5246e) |

In the PR I've updated the global content width to 960px, which addresses the content width inconsistency, but do we want to move the search box to align with the breadcrumbs too?

**Comment by fcoveram** [comment]
I might have missed the discussion somewhere here or in a different ticket, but the initial idea currently documented in mockups, was to have a border between search input and left-aligned content. Here is a screenshot.

![Mockups of Documentation pages cropped in header area](https://github.com/WordPress/wporg-developer/assets/895819/d83ebad4-1bf2-42de-a5b9-21609eccf281)

Do you remember this change @jasmussen?

**Comment by jasmussen** [comment]
I don't recall the full details. Could it be part of the three column view, where the search is part of the left hand chapter navigation, which scrolls independently? If it has to still sit above a border, it might take up a great deal of whitespace to the right of the search box.

**Comment by pkevan** [comment]
I know it's not called out directly here, but it would be nice to have bigger width code snippets, since often you're having to scroll quite a bit to the right, a good example is the source of WP_Query: https://developer.wordpress.org/reference/classes/wp_query/#source.

![Screenshot 2024-02-09 at 15 50 21](https://github.com/WordPress/wporg-developer/assets/2290623/7c2f2adc-c37a-4fe4-b846-fafe86330b3c)

Example on a very large width screen.

**Comment by fcoveram** [comment]
Now I remember previous chats you Joen and I had about the general reduction of white space in layouts. Blending breadcrumb and search with the content area reduces the spacing in between.

If that continues to be our approach, then something like the mockup below should work.

![Documentation pages without border below search input](https://github.com/WordPress/wporg-developer/assets/895819/dbfde8bb-571f-405e-8a39-7d3dbc5299f7)

Regardless the above, the content area in [these examples](https://github.com/WordPress/wporg-developer/issues/484#issuecomment-1935083886) looks better when it's aligned on the left.

**Comment by adamwoodnz** [comment]
> I know it's not called out directly here, but it would be nice to have bigger width code snippets, since often you're having to scroll quite a bit to the right, a good example is the source of WP_Query: https://developer.wordpress.org/reference/classes/wp_query/#source.

Good call! The effect of moving the code reference pages to the 3 column layout, and increasing the content width, is that the code snippet width will increase. For example here is the before and after on the most common desktop size of 1920x1080, where the content width is the full 960px:

| Before | After |
|-|-|
| ![developer wordpress org_reference_classes_wp_query_(1 1920x1080)](https://github.com/WordPress/wporg-developer/assets/1017872/6554f7f0-0c74-4f34-9a7a-62fc7d67d78e) | ![developer wordpress org_reference_classes_wp_query_(1 1920x1080) (1)](https://github.com/WordPress/wporg-developer/assets/1017872/a12261f7-3190-4840-a5f3-39aff204ebbd) |

See more on the [PR](https://github.com/WordPress/wporg-developer/pull/499).

**Comment by adamwoodnz** [comment]
> Regardless the above, the content area in [these examples](https://github.com/WordPress/wporg-developer/issues/484#issuecomment-1935083886) looks better when it's aligned on the left.

The linked examples are on a wide desktop screen where the main column is at the 1160px width limit, and is centered.

| Current (680px) | 960px with realigned search |
|-|-|
| ![developer wordpress org_reference_since_6 4 0_(1 1920x1080)](https://github.com/WordPress/wporg-developer/assets/1017872/5f6c9111-0fd9-4f80-bf25-7d34f3d86b42) | ![localhost_8888_reference_since_6 4 0_(1 1920x1080) (1)](https://github.com/WordPress/wporg-developer/assets/1017872/eea5dd85-80f1-425a-9af5-5f9eb2f5246e) |

Are you saying the main column should not behave like this, and should span the full width, left aligned, like this?

![localhost_8888_reference_since_6 4 0_(1 1920x1080) (2)](https://github.com/WordPress/wporg-developer/assets/1017872/3c548f72-75d8-4a3e-ad3d-343c4c5d2a9f)

**Comment by ryelle** [comment]
> Are you saying the main column should not behave like this, and should span the full width, left aligned, like this?

I think it would still max out at whatever that content max value is (1160?), just left-aligned.

Also, for reference, here's the convo where we decided to center these columns in Documentation: https://github.com/WordPress/wporg-documentation-2022/issues/15

**Comment by adamwoodnz** [comment]
> but do we want to move the search box to align with the breadcrumbs too?

OK, it seems we have the content width and alignment agreed, but I'm still not sure whether to align the search with the breadcrumbs or the content.

**Comment by fcoveram** [comment]
> I think it would still max out at whatever that content max value is (1160?), just left-aligned.

Exactly this.

> Also, for reference, here's the convo where we decided to center these columns in Documentation: https://github.com/WordPress/wporg-documentation-2022/issues/15

Thanks! I was curious about where the decision came from. For this new design, that applies most layout and text styles per section group, left alignment looks better.

**Comment by fcoveram** [comment]
> but do we want to move the search box to align with the breadcrumbs too?

Yes. Align breadcrumb, search, and main content area to the left.

**Comment by ndiego** [comment]
Just catching up here after being away. Looking great, and I defer to @fcoveram for all design direction 🙏

**Comment by adamwoodnz** [comment]
> > but do we want to move the search box to align with the breadcrumbs too?
> 
> Yes. Align breadcrumb, search, and main content area to the left.

Sorry I still don't understand what to do here. I'm hearing that everything should be aligned left, but also that the content width should be restricted and it should be centered, which is conflicted.

At 1320px all those elements will align left and all is well:

![localhost_8888_reference_since_6 4 0_](https://github.com/WordPress/wporg-developer/assets/1017872/09ae25a5-a0b8-4ded-804c-529e75218861)

Above that point my understanding is that the main content will be restricted to 1160px and centered. The local nav and breadcrumbs will still be positioned to the left of the screen. Should search align with the content (A), or the breadcrumbs (B), or should there be no width constraint on the content, and the whole screen align left (C)?

### Screenshots (at 1920px wide)

| A | B | C |
|-|-|-|
| ![localhost_8888_reference_since_6 4 0_(1 1920x1080) (3)](https://github.com/WordPress/wporg-developer/assets/1017872/eb79b2f0-3e07-42f4-a18a-265ba78bfc2c) | ![localhost_8888_reference_since_6 4 0_(1 1920x1080) (1)](https://github.com/WordPress/wporg-developer/assets/1017872/eea5dd85-80f1-425a-9af5-5f9eb2f5246e) | ![localhost_8888_reference_since_6 4 0_(1 1920x1080) (4)](https://github.com/WordPress/wporg-developer/assets/1017872/edfdbe5e-9da5-4208-ad80-2c3553d90328) |

**Comment by fcoveram** [comment]
Sorry for the confusion. I wanted to say that [option C](https://private-user-images.githubusercontent.com/1017872/304620248-edfdbe5e-9da5-4208-ad80-2c3553d90328.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDE5NjIsIm5iZiI6MTcwNzkwMTY2MiwicGF0aCI6Ii8xMDE3ODcyLzMwNDYyMDI0OC1lZGZkYmU1ZS05ZGE1LTQyMDgtYWQ4MC0yYzM1NTNkOTAzMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMDkwNzQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODU4ZGE3MDlhODYyYWNmNTRiNzZmYzcxYWY1ZGFkYzNiZjllNTM5YTNjNGNhMzQ2ZmRiYThmYTRkZDgxOTg4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H5cfcSyo8I3gc4EeKPqCNhtJagI8-ZXvCPasu8aT_ts) from your screenshots is the outcome I expect.

**Comment by ryelle** [comment]
I think there should still be a max-width on that content though, even though it's unlikely anything in this view would expand past it — so that it would be like this:

![](https://github.com/WordPress/wporg-developer/assets/541093/06aa07b9-6b17-4d9c-8cc4-ddb899243751)

You can do that on the container group with `"layout":{"type":"constrained","justifyContent":"left"}`.

**Comment by pkevan** [comment]
> > I know it's not called out directly here, but it would be nice to have bigger width code snippets, since often you're having to scroll quite a bit to the right, a good example is the source of WP_Query: https://developer.wordpress.org/reference/classes/wp_query/#source.
> 
> Good call! The effect of moving the code reference pages to the 3 column layout, and increasing the content width, is that the code snippet width will increase. For example here is the before and after on the most common desktop size of 1920x1080, where the content width is the full 960px:
> 
> See more on the [PR](https://github.com/WordPress/wporg-developer/pull/499).

I wonder if there is a place for a "distraction free mode" or similar, where you can collapse the sidebar too - as useful as a fixed sidebar might appear, it's not always what you are looking for as a user.

**Comment by adamwoodnz** [comment]
> I wonder if there is a place for a "distraction free mode" or similar, where you can collapse the sidebar too

We have [an issue for collapsing the chapter list](https://github.com/WordPress/wporg-developer/issues/306), it was included as a non-essential feature. Collapsing the Table of Contents as well hasn't been discussed afaik.
