### ISSUE TITLE
Establish consistent title and heading typography across all Learn sub-sections

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#488]
> [!NOTE]
> This issue applies to [Developer Resources](https://developer.wordpress.org/), [Documentation](https://wordpress.org/documentation/), [Learn WordPress](https://learn.wordpress.org/) and [Forums](https://wordpress.org/support/forums/), but since Developer Resources has the latest redesign, any PRs that are created from this issue should likely start here ([wporg-developer](https://github.com/WordPress/wporg-developer/))

In the recent Developer Resource redesign, we added a new font for headings called IBM Plex Mono. While this looks great, we are starting to see some inconsistency with other upcoming designs for other Learn sub-sections of WordPress.org. I feel that whatever title and heading fonts we choose should be consistent across all sites. 

I have included examples from the live Developer Resources and the Figma designs for Documentation and Learn WordPress. 

Personally, I really like the sans-serif fonts used for heading in the Developer Resources and Learn WordPress designs. No preference on whether that is Inter or IBM Plex Mono. For the titles, it might be nice to use Garamond since that is used throughout WordPress.org, but I leave that to Design. 

### Developer Resources
| Developer Resources (Home) | Developer Resources (Single) |
|-|-|
|<img width="1369" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/3caee631-6ec9-48ae-ab5e-7e15b2d0e582">|<img width="1497" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/6659c08b-4c02-421d-b247-15d14ce3633e">|

[Live link](https://developer.wordpress.org/) | Uses Inter and IBM Plex Mono

### Documentation
| Documentation (Home) | Documentation (Single) |
|-|-|
|<img width="860" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/213fb130-4753-41df-ae9b-30479af087da">|<img width="856" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/68502975-ff54-495a-a3e4-f14c304709c1">|

[Figma link](https://www.figma.com/file/iM8I9yAYbwjbc9q9b2WWui/Documentation%2FHelpHub) | Uses Inter and Garamond

### Learn WordPress
| Learn WordPress (Home) | Learn WordPress (Single) |
|-|-|
|<img width="908" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/bae7121d-09d4-4648-b024-22e13e11d227">|<img width="911" alt="image" src="https://github.com/WordPress/wporg-developer/assets/4832319/afbf4f40-4d6c-41ff-8264-a7282ca86729">|

[Figma link](https://www.figma.com/file/ZKaf6u8mIHkAanluWafXAp/Learn?type=design) | Uses Inter and Garamond

cc @fcoveram @marko-srb @joen

**Comment by askdesign** [comment]
Great work. I appreciate these efforts toward consistency. My thoughts and preferences:
- Heading: As much as I love Garamond, I do see that it might not be as readable when knocked out white on the dark background. 
- Heading: I lean toward using 1 sans serif throughout. Retain the Inter for the Headings as well as body text.
- Titles: For contrast, I vote for the Garamond, which reads fine when black on light  background.

**Comment by fcoveram** [comment]
I created the ticket #490 that addresses this request.
