### ISSUE TITLE
Block Editor Handbook: Improve it on Github links are broken

### ISSUE THREAD

**Issue by ryanwelcher** [WordPress/wporg-developer#513]
All links I've spot checked in the Block Editor handbook have broken links.

The `href`s are  appended with `[article_edit_link]`.

For example: https://developer.wordpress.org/block-editor/

The link goes to : https://developer.wordpress.org/block-editor/[article_edit_link]

![Block_Editor_Handbook___Developer_WordPress_org](https://github.com/WordPress/wordpress.org/assets/1259027/99d24b9c-d328-4cb8-a730-72c9fba1e8c9)

Note: requires Gutenberg 18.1+ to reproduce

**Comment by dd32** [comment]
_Transferring issue to correct repo_

I'm unable to duplicate.

All the links are correct for me, and `curl https://developer.wordpress.org/block-editor/ | grep 'article_edit_link'` shows nothing.

Note, that that is the shortcode being used though, which suggests shortcodes weren't applying (Which you cal also see from the `[last_updated]` shortcode being present in the image)

https://github.com/WordPress/wporg-developer/blob/trunk/source/wp-content/themes/wporg-developer-2023/patterns/article-meta.php#L17

https://github.com/WordPress/wporg-developer/blob/trunk/source/wp-content/themes/wporg-developer-2023/inc/shortcodes.php#L28-L41

**Comment by adamwoodnz** [comment]
Sorry, slow to update the ticket. This happened earlier today when we unpinned Gutenberg and switched to trunk. With trunk [the hook we are using to process shortcodes in patterns](https://github.com/WordPress/wporg-parent-2021/blob/e88d9fc6b20bff0f1021ec4dcd5f9dfdb69fb406/source/wp-content/themes/wporg-parent-2021/functions.php#L19-L29) stopped firing (see https://github.com/WordPress/gutenberg/pull/60349), so we have rolled back. We still need a long term solution.

**Comment by ryanwelcher** [comment]
Looks like this is resolved and this issue is in the wrong place so I'll close this ticket.

**Comment by ryelle** [comment]
It looks like shortcodes do work as normal block content, but not in attributes. Depending on the outcome of https://github.com/WordPress/wporg-parent-2021/issues/136, we might want to reopen this to switch out for shortcodes in core blocks, or maybe block bindings.

For example, these shortcodes work, but you can see the `last_updated` heading isn't rendered.

```
<!-- wp:paragraph -->
<p>[article_edit_link]</p>
<!-- /wp:paragraph -->

<!-- wp:button {"className":"is-small"} -->
<div class="wp-block-button is-small"><a href="[article_edit_link]" class="wp-block-button__link wp-element-button"><?php esc_html_e( 'Edit', 'wporg' ); ?></a></div>
<!-- /wp:button -->
```
<img width="1000" alt="Screenshot 2024-05-07 at 1 06 37 PM" src="https://github.com/WordPress/wporg-developer/assets/541093/2b47a436-2cce-488e-bf57-2a9cb347f7e8">
