### ISSUE TITLE
Add the WordPress Playground Block plugin

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-developer#520]
The Playground Block plugin registers a block that displays WordPress Playground instances in post content. The plugin is available in the [WordPress.org repository](https://wordpress.org/plugins/interactive-code-block/) and is maintained [on GitHub](https://github.com/WordPress/playground-tools/tree/trunk/packages/wordpress-playground-block) by WordPress contributors. 

Enabling the block on the developer.wordpress.org multisite will allow us to display code examples alongside live previews in Handbooks that are currently using blocks (like [Themes](https://developer.wordpress.org/themes/)). Instead of just presenting a code example, readers will be able to see the example in action and interact with the code. I believe this will improve the developer education experience for both extenders and Core contributors.

I am not sure what the vetting process is for new plugins on WordPress.org, so please let me know if additional information is needed. Also, if this issue should be opened in a different repo, or on Trac, I'm happy to move it.

**Comment by adamwoodnz** [comment]
The plugin is already installed on the network, and is already activated on Learn. Any reason not to activate on Developer too @dd32 @StevenDufresne ?

**Comment by StevenDufresne** [comment]
Should be fine to turn on.

**Comment by adamwoodnz** [comment]
It seems the plugin still hasn't completed an accessibility review, see https://wordpress.slack.com/archives/C01KC5VDQBC/p1717035971866509?thread_ts=1717011768.294689&cid=C01KC5VDQBC

**Comment by adamwoodnz** [comment]
I've created a test page on the Learn staging site at https://learn.wordpress.org/test/wordpress-playground-block-plugin-test-page/ for this testing

**Comment by ndiego** [comment]
cc @adamziel regarding the [accessibility review](https://wordpress.slack.com/archives/C01KC5VDQBC/p1717035971866509?thread_ts=1717011768.294689&cid=C01KC5VDQBC) discussion.

**Comment by adamwoodnz** [comment]
FYI we're using the block on Learn now. There is only [1 open a11y issue](https://github.com/WordPress/playground-tools/issues/290) remaining on the [board](https://github.com/WordPress/playground-tools/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+label%3AAccessibility), which looks like it has been addressed, but not closed yet.

I think we're safe to activate this now.

**Comment by adamwoodnz** [comment]
I have now activated the Playground block plugin on developer.wordpress.org
