### ISSUE TITLE
When the source block is empty, the code container is still visible.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#58]
Most likely related to #44.

There are functions that don't havecode in source code block:
[media_date_column_time](https://developer.wordpress.org/reference/hooks/media_date_column_time/)

Since we use a new block to render the source code, when there is no code, the code container is still visible.

![](https://d.pr/i/epmrbc.png)

**Comment by ryelle** [comment]
I see source code on that hook:

<img width="953" alt="Screen Shot 2022-06-02 at 10 47 11 AM" src="https://user-images.githubusercontent.com/541093/171656542-b52afe85-b05c-4938-b27d-527015a71422.png">

**Comment by StevenDufresne** [comment]
Do you see it in the link above? Which is a link to the live site:
[https://developer.wordpress.org/reference/hooks/media_date_column_time/](https://developer.wordpress.org/reference/hooks/media_date_column_time/)

**Comment by ryelle** [comment]
No, it's not on production, it was added in https://github.com/WordPress/wporg-developer/pull/28
