### ISSUE TITLE
Should we keep around "moved" code pages?

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-developer#61]
If you click on the database link in the API section on the homepage.

<img src="https://d.pr/i/0jdmFc.png" width="300px">

It goes to [https://codex.wordpress.org/Database_API](https://codex.wordpress.org/Database_API) which tells you to move on.

<img src="https://d.pr/i/uohPkn.png" width="300px">

**Can we not just link to the final document? What's the history here?**

**Comment by ryelle** [comment]
On production these use a nav menu with the correct links, but on our test sites that menu isn't set up, so it falls back to the codex links. We could update the fallbacks, but aside from dev sites, I'm not sure when these would even show up.

https://github.com/WordPress/wporg-developer/blob/f331cf1579af81f13ec4a974360f42d3166f10d1/source/wp-content/themes/wporg-developer/page-reference-landing.php#L77-L90

**Comment by StevenDufresne** [comment]
Aha! I don't think we care right now.
