### ISSUE TITLE
Handbook: Check that the `code` shortcode is imported correctly when SyntaxHighlighter is disabled

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-developer#84]
This line in the markdown parser makes it sound like it might not transform the markdown code blocks into the `[code…]` shortcode if it can't find the SyntaxHighlighter class. If we want to disable that plugin, this might be an unexpected side effect.

https://github.com/Automattic/jetpack/blob/19992e36463b6b12981ea5857785484b0deca243/projects/plugins/jetpack/_inc/lib/markdown/gfm.php#L62

**Comment by adamwoodnz** [comment]
Syntax Highlighter is deactivated, new theme is launched, and no issues reported.
