### ISSUE TITLE
Source block is very long on some pages, no expand/collapse

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-developer#86]
http://localhost:8888/reference/classes/wp_query/get_posts/

..currently shows a Source block with 3k+ lines fully expanded. There are no expand/collapse buttons.

There's an issue #22 for changes to the expand/collapse logic. I think that was referring more to examples the description rather than the Source block itself. Either way we should implement some kind of height limit to the source block, whether or not it expands.

**Comment by ryelle** [comment]
Personally I assumed the  expand/collapse logic proposed in https://github.com/WordPress/wporg-developer/issues/22#issuecomment-1140675129 would apply to all code blocks, rather than just specific examples.

**Comment by dd32** [comment]
Expand/collapse restored in #88
