### ISSUE TITLE
Expand argument arrays in the function reference

### ISSUE THREAD

**Issue by tellyworth** [WordPress/wporg-developer#95]
### Discussed in https://github.com/WordPress/wporg-developer/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **tellyworth** May 27, 2022</sup>
Many WP functions use some form of `$args` array parameter, which leads to docs like this:

https://developer.wordpress.org/reference/functions/wp_update_post/
<img width="1049" alt="Screen Shot 2022-05-27 at 4 44 08 pm" src="https://user-images.githubusercontent.com/7200686/170645925-c22c8dbf-0142-4c1d-917b-236a81f3d87f.png">

It would be great to pull in and expand the details of the array arguments so it's not necessary to click through to another page.
</div>

**Comment by iandunn** [comment]
I think this was fixed by #96
