### ISSUE TITLE
Anchor before Source heading missing

### ISSUE THREAD

**Issue by dd32** [WordPress/wporg-developer#98]
The Source heading is lacking an anchor icon, made more evident by #46.

<img width="355" alt="Screen Shot 2022-06-08 at 7 07 04 pm" src="https://user-images.githubusercontent.com/767313/172578421-74c462f4-e5f6-48c7-af8f-a29860f272d2.png">

This is caused by https://github.com/WordPress/wporg-developer/blob/673d9d888aae8c2e1e9adcc3d8df6bbbd0f772fb/source/wp-content/themes/wporg-developer/scss/main.scss#L1340-L1342 - I'm not sure what the purpose of that rule originally was.

**Comment by ryelle** [comment]
This will be fixed by https://github.com/WordPress/wporg-developer/pull/90 — that `overflow` isn't necessary since there's an overflow on the `pre` (it was likely to prevent the code overflowing).

**Comment by StevenDufresne** [comment]
Appears to be fixed in #90.
